### PR TITLE
Introduce scheduleWithFixedDelay for scheduling instead of AtFixedRat…

### PR DESCRIPTION
**Pull request by kgoderis**
…e + automatic formatting unfortunately

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Why does this PR show 2,401 additions and 2,670 deletions?

**Comment by kgoderis** [comment]
Due to the automatic code formatting upon saving files In the oomph provided IDE

**Comment by kgoderis** [comment]
stupid question but is there a way to put different commits in different pull requests? Commits are simply added to the open pull request, even if they have nothing to do with the other commits in the PR

**Comment by maggu2810** [comment]
Create a new branch for the further commits...

**Comment by kaikreuzer** [comment]
This PR has been replaced by individual ones.

**Pull request closed without merging**
