### PR TITLE
added initial BluetoothLE binding

### PR DESCRIPTION
**Pull request by pamapa**
This is a first try to support Bluetooth low energy devices.

Unfortunately there exists no java library for Linux to support Bluetooth low energy. Therefore i have decided to write a small bridge c program. The bridge does a low energy scan and translates the bluetooth low energy advertisments frames to UDP packets.

Currently only the "FreeTec Bluetooth 4.0-Thermometer" is supported, it will be very easy to support more 
"ADV_NONCONN_IND - Non connectable undirected advertising (3)" devices. The c bridge code might be extended later to also support other devices classes (e.g ADV_DIRECT_IND).

I am a bit uncertain about the timings in the bridge c program. In order to safe energy on the device i try to scan not too often. This will need more considerings.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hi,

Thanks a lot for this contribution and sorry that it took so long for me to respond!
Before going into a detailed code review, I would like to discuss with your the scope of this binding:
BLE is definitely an important protocol to support, so I would like to get this right, i.e. powerful and extensible.

As you point out, there is no BLE standard library available in Java, which is really a pity. Using a C bridge with a TCP connection sounds like a fair solution to this problem, although it obviously introduces some platform dependency and makes the build of a binary much harder.
Can you tell me what requirements are there on the OS side for this solution? Is BlueZ required? Does it work with ANY BLE dongle / module or just specific ones? I am not yet an expert on this...
Is HCI the only/best way to access BLE dongles or are there any alternatives that should be considered as well?

With respect to the architecture, I wonder if some low level functionality should be moved into an org.openhab.transport.io.ble bundle, which could offer a generic BLEDiscoveryService (similar to the UPnPDiscoveryService) and the raw level communication stuff. Bindings could then be added that support specific devices, so this would be very modular and extensible.

Would it maybe also make sense to add some GATT library (like https://github.com/movisens/SmartGattLib) as a higher level of abstraction? 

Hoping you can help on those questions with your expertise!

**Comment by kaikreuzer** [comment]
@pamapa , I am closing this PR as you do not seem to follow up on it anymore. In case you are back to follow up on this PR, please feel free to reopen it at any time!

**Comment by kubawolanin** [comment]
It's a closed issue now, but maybe someone who'll want to try to implement BLE binding in the future may find it interesting.
There's this project called [TinyB](https://github.com/intel-iot-devkit/tinyb/) which is utilizing BlueZ.
I'm not an expert in the field - just wanted to share what I've found.

**Comment by kaikreuzer** [comment]
@kubawolanin Note that a BLE binding is in the pipeline at https://github.com/eclipse/smarthome/pull/551.

TinyB has also already been briefly discussed on it: https://github.com/eclipse/smarthome/pull/551#issuecomment-235431577

**Pull request closed without merging**
