### PR TITLE
added missing jetty 9.2.9 dependencies

### PR DESCRIPTION
**Pull request by teichsta**
Signed-off-by: Thomas Eichstädt-Engelen <thomas@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Why do you also deselect the following bundles:
- org.openhab.binding.max
- org.openhab.binding.sonos
- org.openhab.core.compat1x
- org.openhab.io.transport.serial

**Comment by kaikreuzer** [comment]
And which Jetty dependencies are missing? It all starts up nicely for me.

**Comment by teichsta** [comment]
> And which Jetty dependencies are missing? It all starts up nicely for me.

Strange! In my environment the bundles: jetty.server, jetty.util, jetty.servlet and some others (around 6) were missing.

**Comment by teichsta** [comment]
> Why do you also deselect the following bundles:

i think removed them already because the default LaunchConfig should only refer to Bundles that are needed to run the demo configuration. The individual setups are totally different but these minimal configuration should work for everybody.

**Comment by kaikreuzer** [comment]
> i think removed them already because the default LaunchConfig should only refer to Bundles that are needed to run the demo configuration

It is the same setup as it is built for the demo zip, so I think it makes sense as it is for the moment. Once the list of bindings gets longer, things will look different of course.

**Pull request closed without merging**
