### PR TITLE
Binding documentation

### PR DESCRIPTION
**Pull request by robbyb67**
As requested, I hope the full example is correct ...

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Great, thanks! May I ask you to sign-off your commit before I merge?

**Comment by kaikreuzer** [comment]
hm, somehow here are 3 commits. Could you try to either squash them or create a new PR?

**Comment by kaikreuzer** [comment]
@robbyb67, would you be able to squash this today?

**Comment by robbyb67** [comment]
Sorry for being late this time ...

**Comment by kaikreuzer** [comment]
Still on time - thanks a lot!

**Pull request merged**
