### PR TITLE
Karaf: merge master

### PR DESCRIPTION
**Pull request by maggu2810**
Nothing to do as this change has already been done in this branch.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
this does not include any file changes...?

**Comment by maggu2810** [comment]
This PR merges 25bf2fe.
JmDNS has been already part of the Karaf launch config.
IIRC: You added it as you tested this branch in the Eclipse IDE

**Comment by maggu2810** [comment]
343758ddc26c8724d7091b59bce84111a5d6660e

**Comment by kaikreuzer** [comment]
so we can close this PR unmerged?

**Comment by maggu2810** [comment]
Ahm, no. It would be nice if you would merge it.
* 25bf2fe is in the master branch
* so it must be changed at some time, if we merge the master (git parent commits mechanism)
* as the change is already part of this branch we will get a conflict
* this conflict is solved in 52ac95e

If no change in a merge commit does not mean it does not need to be done.
If we would like to merge branch1 to branch2, every commit of branch1 must be merged in branch2 (and sometime conflicts have to be resolved using the merge commit).

**Comment by kaikreuzer** [comment]
alright then :-)

**Pull request merged**
