### PR TITLE
bundle all additional features and artifacts

### PR DESCRIPTION
**Pull request by maggu2810**
It is not the best solution, but a working one.
We could do it much better later, but ATM it seems as we need it.

The "user" should not be involved if we do it later in a much more cleaner way...

### CODE REVIEW

**Comment by maggu2810** [comment]
@kaikreuzer Please test, if this is working for you...

**Comment by kaikreuzer** [comment]
Will do, thanks!

**Comment by kaikreuzer** [comment]
It works to some extend; the jars are packaged, but somehow only the ESH and OH2 features are found, but not OH1 ones. `feature:install openhab-binding-hue` works and `feature:install openhab-binding-sonos` as well. But `feature:install openhab-binding-http` fails with
```
2015-11-24 09:35:21.633 [WARN ] [url.mvn.internal.AetherBasedResolver] - Error resolving artifactorg.openhab.binding:org.openhab.binding.http:jar:1.8.0-SNAPSHOT:Could not find artifact org.openhab.binding:org.openhab.binding.http:jar:1.8.0-SNAPSHOT
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.openhab.binding:org.openhab.binding.http:jar:1.8.0-SNAPSHOT
```

Note that I have removed (renamed) my local Maven repo `.m2/repository` so that artifacts cannot be downloaded from there.

Any idea what is different with the OH1 bundles?

**Comment by maggu2810** [comment]
It seems to be related that unique timestamps are used.

```text
6345  stat("/home/.../distributions/openhab-runtime-karaf/target/assembly/system/org/openhab/binding/org.openhab.binding.http/1.8.0-SNAPSHOT/maven-metadata-local.xml", {st_mode=S_IFREG|0644, st_size=587, ...}) = 0
6345  stat("/home/.../distributions/openhab-runtime-karaf/target/assembly/system/org/openhab/binding/org.openhab.binding.http/1.8.0-SNAPSHOT/maven-metadata-local.xml", {st_mode=S_IFREG|0644, st_size=587, ...}) = 0
6345  open("/home/.../distributions/openhab-runtime-karaf/target/assembly/system/org/openhab/binding/org.openhab.binding.http/1.8.0-SNAPSHOT/maven-metadata-local.xml", O_RDONLY) = 225
6345  stat("/home/.../distributions/openhab-runtime-karaf/target/assembly/system/org/openhab/binding/org.openhab.binding.http/1.8.0-SNAPSHOT/org.openhab.binding.http-1.8.0-20151122.020014-121.jar", 0x7f182d7708c0) = -1 ENOENT (No such file or directory)
```

If I look at <code>system/org/openhab/binding/org.openhab.binding.http/1.8.0-SNAPSHOT/maven-metadata-local.xml</code>
```text
<?xml version="1.0" encoding="UTF-8"?>
<metadata modelVersion="1.1.0">
  <groupId>org.openhab.binding</groupId>
  <artifactId>org.openhab.binding.http</artifactId>
  <version>1.8.0-20151122.020014-121</version>
  <versioning>
    <snapshot>
      <localCopy>true</localCopy>
    </snapshot>
    <lastUpdated>20151123091505</lastUpdated>
    <snapshotVersions>
      <snapshotVersion>
        <extension>jar</extension>
        <value>1.8.0-20151122.020014-121</value>
        <updated>20151123091505</updated>
      </snapshotVersion>
    </snapshotVersions>
  </versioning>
</metadata>
```

**Comment by maggu2810** [comment]
Could you check the build system options for OH1 and OH2 if OH1 uses the unique timestamp option on deploy and OH2 don't use it?

**Comment by kaikreuzer** [comment]
Well, the problem is that Maven 3 always uses unique timestamps when deploying artifacts to a remote repo (http://stackoverflow.com/questions/4275466/how-do-you-deal-with-maven-3-timestamped-snapshots-efficiently?answertab=votes#tab-top). So the difference is that the other artifacts are packaged from my local maven repo, where they are simply SNAPSHOT. I guess if I'd run an openHAB 1 build locally first, it would work as well - but we will need a solution that is capable of using the downloaded artifacts.

**Comment by maggu2810** [comment]
If I have a look at the Apache Karaf used features, the artifacts used in the features are added to the pom of the feature (scope provided). If we do that, then the files should be downloaded by maven to fit the dependencies before and could be taken from the local repo. Perhaps we could try that...

**Comment by kaikreuzer** [comment]
> Perhaps we could try that...

Sounds like a plan. You or me?

**Comment by maggu2810** [comment]
I have added:

```text
        <dependency><groupId>${dep.bsn.org.eclipse.paho.client.mqttv3.groupId}</groupId><artifactId>${dep.bsn.org.eclipse.paho.client.mqttv3.artifactId}</artifactId><version>${dep.bsn.org.eclipse.paho.client.mqttv3.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>${dep.bsn.org.eclipse.smarthome.ui.paperui.groupId}</groupId><artifactId>${dep.bsn.org.eclipse.smarthome.ui.paperui.artifactId}</artifactId><version>${dep.bsn.org.eclipse.smarthome.ui.paperui.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>${dep.bsn.org.jupnp.groupId}</groupId><artifactId>${dep.bsn.org.jupnp.artifactId}</artifactId><version>${dep.bsn.org.jupnp.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>${dep.jmdns.groupId}</groupId><artifactId>${dep.jmdns.artifactId}</artifactId><version>${dep.jmdns.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.eclipse.smarthome.binding</groupId><artifactId>org.eclipse.smarthome.binding.hue</artifactId><version>${esh.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.eclipse.smarthome.binding</groupId><artifactId>org.eclipse.smarthome.binding.lifx</artifactId><version>${esh.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.eclipse.smarthome.binding</groupId><artifactId>org.eclipse.smarthome.binding.ntp</artifactId><version>${esh.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.eclipse.smarthome.binding</groupId><artifactId>org.eclipse.smarthome.binding.wemo</artifactId><version>${esh.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.eclipse.smarthome.binding</groupId><artifactId>org.eclipse.smarthome.binding.yahooweather</artifactId><version>${esh.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.eclipse.smarthome.io</groupId><artifactId>org.eclipse.smarthome.io.transport.mdns</artifactId><version>${esh.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.eclipse.smarthome.io</groupId><artifactId>org.eclipse.smarthome.io.transport.mqtt</artifactId><version>${esh.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.eclipse.smarthome.io</groupId><artifactId>org.eclipse.smarthome.io.transport.upnp</artifactId><version>${esh.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.eclipse.smarthome.ui</groupId><artifactId>org.eclipse.smarthome.ui.classic</artifactId><version>${esh.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.action</groupId><artifactId>org.openhab.action.mail</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.action</groupId><artifactId>org.openhab.action.pushover</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.action</groupId><artifactId>org.openhab.action.xbmc</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.action</groupId><artifactId>org.openhab.action.xmpp</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.addons.io</groupId><artifactId>org.openhab.io.myopenhab</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.anel</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.astro</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.astro</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.autelis</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.avmfritz</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.comfoair</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.denon</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.dmx</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.dmx.ola</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.dscalarm</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.energenie</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.enocean</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.epsonprojector</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.exec</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.freebox</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.freeswitch</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.fs20</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.hdanywhere</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.heatmiser</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.homematic</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.http</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.ihc</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.insteonplm</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.ipp</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.keba</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.knx</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.lcn</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.lutron</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.max</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.milight</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.modbus</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.network</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.networkhealth</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.nibeheatpump</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.onewire</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.onkyo</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.openenergymonitor</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.owserver</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.pioneeravr</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.pulseaudio</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.rfxcom</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.samsungac</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.satel</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.smaenergymeter</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.snmp</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.sonos</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.squeezebox</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.swegonventilation</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.systeminfo</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.tellstick</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.tesla</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.tinkerforge</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.vitotronic</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.weather</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.wol</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.xbmc</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.binding</groupId><artifactId>org.openhab.binding.zwave</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.bundles.io</groupId><artifactId>org.openhab.io.transport.serial</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.bundles.ui</groupId><artifactId>org.openhab.ui.iconset.classic</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.io</groupId><artifactId>org.openhab.io.multimedia.tts.marytts</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.io</groupId><artifactId>org.openhab.io.transport.cul</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.persistence</groupId><artifactId>org.openhab.persistence.jpa</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.persistence</groupId><artifactId>org.openhab.persistence.logging</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.persistence</groupId><artifactId>org.openhab.persistence.mysql</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.persistence</groupId><artifactId>org.openhab.persistence.rrd4j</artifactId><version>${oh1.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.ui</groupId><artifactId>org.openhab.ui.classicui</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.ui</groupId><artifactId>org.openhab.ui.cometvisu</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
        <dependency><groupId>org.openhab.ui</groupId><artifactId>org.openhab.ui.paperui</artifactId><version>${project.version}</version><scope>provided</scope></dependency>
```

this downloads the artifacts, but don't help.

**Comment by kaikreuzer** [comment]
:-(

**Comment by maggu2810** [comment]
Will try to have a look at this at the evening.

**Comment by maggu2810** [comment]
This should also raise a problem if we are using snapshot dependencies. So, no blocker for a fixed version (if I don't miss something).
But sure, it has to be fixed.

**Comment by maggu2810** [comment]
<pre>Well, the problem is that Maven 3 always uses unique timestamps when deploying artifacts to a remote repo</pre>
It defaults to true, but could be disabled.
https://maven.apache.org/plugins/maven-deploy-plugin/deploy-file-mojo.html#uniqueVersion

On my jenkins it is a configuration option of the job, if it should be enabled or disabled (IIRC it is disabled on jenkins default).

**Comment by kaikreuzer** [comment]
Are you sure that it works? According to https://cwiki.apache.org/confluence/display/MAVEN/Maven+3.x+Compatibility+Notes#Maven3.xCompatibilityNotes-Non-uniqueSnapshotDeployments, this setting is simply ignored by Maven 3.

**Comment by maggu2810** [comment]
No :confused: never checked the result

**Comment by maggu2810** [comment]
FYI

<pre>feature:install openhab-binding-hue works and feature:install openhab-binding-sonos as well.</pre>

This did not work for me if I am using an empty local maven repo.

We have to remove all the maven-metadata files that refers to the timestamped version.
<pre>find system -name "maven-metadata-local.xml" -delete</pre>
works for me.

**Comment by maggu2810** [comment]
Perhaps we need to fix and create a PR...

https://github.com/apache/karaf/blob/master/tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/KarMojo.java#L259

**Comment by kaikreuzer** [comment]
> We have to remove all the maven-metadata files that refers to the timestamped version.

Could we for the time being add this to the assembly configuration to filter these resources?

**Comment by maggu2810** [comment]
apache/karaf#102

**Comment by maggu2810** [comment]
I rebased my changes for the karaf-maven-plugin from master to karaf-4.0.3.
I pushed it here: https://github.com/maggu2810/karaf/tree/k403-pr102

The quick and dirty solution if to build the karaf-maven-plugin with the changes but kept the version to 4.0.3
```bash
tooling/karaf-maven-plugin
mvn clean install -DskipTests
```

Changes the groupId / version for the plugin alone is complicated as it is reused internally (normal e.g. ${project.version}). If we have a repo we could deploy to, we could try to build the whole Karaf project with another groupId and backport fixes.

WDYT

**Comment by maggu2810** [comment]
I tested with the q'n'd solution and it solves the problem.

**Comment by kaikreuzer** [comment]
Just tested it, it works nicely, thanks! So it seems we now have to wait for a Karaf 4.0.4 release to have this fixed for our build?

**Comment by maggu2810** [comment]
It has been merged upstream. Perhaps we could use the 4.0.4-SNAPSHOT version of the plugin for the kar creation and stay at 4.0.3 for the remaining parts.

**Comment by kaikreuzer** [comment]
> It has been merged upstream.
I saw this yesterday - these guys are really fast in accepting contributions!

> Perhaps we could use the 4.0.4-SNAPSHOT version

Sounds as a plan - could you update the PR accordingly?

**Comment by maggu2810** [comment]
wfm

**Pull request merged**
