### PR TITLE
formatter changes

### PR DESCRIPTION
**Pull request by maggu2810**
WRT https://github.com/eclipse/smarthome/pull/668#issuecomment-162670919

### CODE REVIEW

**Comment by maggu2810** [comment]
After this have be done, we should compare that two files and have a look if there are some differences that should be cleaned up.
But the last changes I have done in the ESH setup file should be covered by this PR.

**Comment by maggu2810** [comment]
Wait a moment, will do it know :wink:

**Comment by maggu2810** [comment]
done

**Comment by kaikreuzer** [comment]
If I look at https://github.com/openhab/openhab2/pull/544/files, something is odd. Would you agree?

**Comment by maggu2810** [comment]
The last added commit (sync ESH and OH2) removed the two files that should be kept untouched.
I have fixed that now.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
