### PR TITLE
Properties setting for MAX! Cube

### PR DESCRIPTION
**Pull request by marcelrv**
MAX! binding properties setting.

Note this is first part of enhancement #201

*Properties setting for MAX! Devices
*Properties setting for MAX! Cube
*Various small typo/cleanup/indents corrections/refactoring to align
* Formats the firmware output
* Get room information for MAX! devices
* Bring devices with RF connection problems offline
* Change configuration for refresh from miliseconds to seconds to make more userfriendly
* Tests for H Messages
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by marcelrv** [comment]
@kaikreuzer 

Please wait with this until @habnefrage PR #185 is merged to avoid disrupting that patch.
If that one gives merge conflicts I'll fix it.

**Comment by marcelrv** [comment]
Also when this code is running it gives error #218 when it runs the first time.
However the following time it is run, no error thrown.

**Comment by kaikreuzer** [comment]
@marcelrv, please rebase squash this PR, then we should be fine to merge it.

**Comment by marcelrv** [comment]
yes, will do that indeed. I also in the mean time did added some more to it, so will see if I lump that in as well or that I'll make a separate PR for it.
Anyways, traveling again and can't really test it well here so will wait couple of days until I'm back,

**Comment by marcelrv** [comment]
@kaikreuzer Okay, testing looked good. squashed now the commits

**Comment by kaikreuzer** [comment]
Thanks Marcel! Just to get it straight: What you call "properties" here are "config parameters" for the things (and not properties, wrt our discussion), right?

**Comment by marcelrv** [comment]
Actually both.
So I update the pre-defined properties (firmware, vendor, model, serial)

For the 'non-predefined' / remaining ones, I update configuration, I'll also configure all the others mentioned in  #201 as configuration.

**Comment by kaikreuzer** [comment]
Ah, you are right, I didn't spot this in the code before.

**Pull request merged**
