### PR TITLE
Fix build error on duplicate id.

### PR DESCRIPTION
**Pull request by dvanherbergen**
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Cool, thanks - the build is green again!

**Comment by dvanherbergen** [comment]
No problem. Can you add me to the build failure notification list? That way I can help to keep it green...

**Comment by kaikreuzer** [comment]
Sure - done. Next one to fix is https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ - I will chase why the openhab-core dependency is not available...

**Comment by dvanherbergen** [comment]
> I will chase why the openhab-core dependency is not available...

Maybe because there is no jenkins build defined for kaikreuzer/openhab-core?

**Comment by kaikreuzer** [comment]
No, I manually deployed it. The problem was that the build is currently configured to use the latest snapshot, but this is not available in JCenter. So https://github.com/openhab/openhab-distro/pull/2/files solves the problem :-)

**Comment by kaikreuzer** [comment]
Seems to be solved now, maybe through the fact that openhab-core is also built on the Jenkins: https://openhab.ci.cloudbees.com/job/openHAB2/467/

**Comment by dvanherbergen** [comment]
After a closer look, it turned out to be the absence of the latest version of openhab2-addons which caused the distro build to fail.
http://oss.jfrog.org/libs-snapshot/org/openhab/addons/openhab2-addons/2.0.0-SNAPSHOT/

**Pull request merged**
