### PR TITLE
Align feature and product names with ESH, also add a binding feature

### PR DESCRIPTION
**Pull request by teichsta**
Signed-off-by: Thomas Eichstädt-Engelen <thomas@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Please note that I have completely removed all Eclipse features in https://github.com/kaikreuzer/openhab2/tree/karaf/features already. So if we proceed with #194, none of your changes will remain. Do you have any real requirements for Eclipse features of openHAB 2?

**Comment by teichsta** [comment]
> Do you have any real requirements for Eclipse features of openHAB 2?

yes, i am currently creating a private solution based on openHAB2. In order to create a reasonable target platform i'd like to add the necessary openHAB2 bundles through these features.

**Comment by teichsta** [comment]
and btw i am fine if these change won't remain in the future :-)

**Comment by kaikreuzer** [comment]
I'm fine with the refactoring of the names, but I am not too keen on introducing a new feature for the bindings as this would mean yet another place to maintain when new bindings are added (and what about other addons?) Would it be ok if you simply create such additional features in your private fork (and thus remove it from the PR)?

**Comment by teichsta** [comment]
> Would it be ok if you simply create such additional features in your private fork (and thus remove it from the PR)?

ok, will do!

**Comment by teichsta** [comment]
> yet another place to maintain when new bindings are added

i would agree, but how can provide the bindings through P2 without adding them to a feature (which then can be added to the target platform in the private project). I assume this is the reason why there is a ESH binding feature as well?

**Comment by teichsta** [comment]
fyi, i've removed the binding feature for now to make quick merging possible …

**Comment by kaikreuzer** [comment]
> but how can provide the bindings through P2 without adding them to a feature

Well, the question is rather: Why should we provide them through P2 while they are available as Maven artefacts? A "feature" that combines all of them does not make much sense, there should rather be a separate feature for every binding (and its optional dependencies). But this is what I want to achieve through Karaf features, not Eclipse features.

**Pull request merged**
