### PR TITLE
H2 SQL Persistence Service

### PR DESCRIPTION
**Pull request by cdjackson**
Just submitting this PR for information/visibility for now. This still needs some work, and possibly some work to improve speed with the schema as I've only done minimal testing so far. The idea is to have a 'quality' (hopefully!) embedded database usable standalone on devices like the Pi and BeagleBone.

H2 is licensed under EPL (and others).

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
@kaikreuzer I was wondering about moving this to ESH - any thoughts?
The aim of this is to have a simple to deploy persistence service with no dependencies for embedded use. The license for H2 looks friendly, but I guess you need to go through IPR review?

**Comment by kaikreuzer** [comment]
Hi Chris, this indeed sounds like an interesting database. Sure, there is no reason not to directly add this to ESH. Reading http://www.h2database.com/html/license.html it seems that H2 is even available under the EPL, so getting the IPR review done should be simple.
Note that we already have MapDB in ESH (not as a persistence service, but as a storage for things etc). This does not support SQL, but for a persistence service this isn't really needed. Did you compare H2 and MapDB? What are the advantages of H2?

**Comment by cdjackson** [comment]
Hi Kai,
Yes - I looked at MapDB - I'd initially hoped to extend the existing MapDB persistence, but it's not really designed for storing (and more importantly, retrieving) large data sets. There is a lot of information that talks about MapDB being used for large data sets, but it's more of a persistent (or even just off heap) Map store. The query and retrieval side looked very clunky. I think MapDB is good for what it's being used for already in ESH, but not so much where we might want to use it for longer term historical data sets with random access...

At least that's what I found...

On the other side, H2, being SQL, is great for queries. The performance, being SQL, probably isn't as good as some options, but according to the H2 website it's the fastest around.

I see H2 being used for more historical data - where data junkies can keep long term data and access it relatively easily - something I'm keen to extend in ESH...

I'm currently running it alongside mySQL server on my OH1 system so I'll be able to benchmark it at some stage soon...

**Comment by kaikreuzer** [comment]
Ok, sounds great, so feel free to move this to ESH once you have stabilised it!

**Comment by cdjackson** [comment]
Some performance information for interest -:

On my Linux box (1.5GHz AMD), I'm returning a query from HABmin with 4 items requested, and around 1600 data points returned in 340ms (MYSQL is around 530ms).

On the BeagleBoneBlack (ARM similar to RPi), 1 days data (where I'm logging every minute) is being returned in around 720ms - this request is for two items, each returns around 1450 data points. HABmin does the requests in parallel so the first response comes in around 720, and the second at 780ms, so the chart is ready in well under a second.

On my Linux box, stores are taking about 2 or 3 ms - MYSQL says 1ms, but it's being processed in a separate process, so this doesn't count.

**Comment by kaikreuzer** [comment]
Sounds pretty promising!
Do you have any figures on database size and growth over time?

**Comment by cdjackson** [comment]
Not much - it will grow unless it’s pruned. I’d like to add some pruning functions, but that said, memory is cheap (even on a Pi!)… Pruning could be handled internally within the persistence service (arguably like rrd does - I know that’s different, but it achieves the same goal) or it could be handled in the persistence manager (which is probably my preference).

However, what I did do the other day is imported 2 million doubles into the database and that as around 120MB - that’s around 4 years of data at 1 minute, but if you log changes it’s typically smaller. In my mySQL database where I log changes and have humidity and temperature logging with 0.1 deg temp or 0.1% humidity, I have between 60 and 130 thousand data points in each table (i.e. an item) for around 21 months of data. So, at 130k samples, 120MB would be 15 years - or 1 year for 15 items…

I would expect that it should be possible to add an SD card with 64GB for a few Euro (which is what I have on the BeagleBone) and then it’s just not a problem anyway...

**Comment by kaikreuzer** [comment]
Sounds pretty good as well. I just had very bad experiences with db4o (which grew past 1 GB within a few weeks), that's why I preferred rrd4j so far. But H2 might indeed be an option that can make me move.

**Comment by kaikreuzer** [comment]
@cdjackson What's the status of this? Do you feel it is stable enough by now? Then feel free to close this PR and open an PR at ESH, so that we can do the further processing there.

**Comment by cdjackson** [comment]
Thomas reviewed the same PR on OH1 last week. I need to go through his comments and update, and will then look at OH2/ESH.

**Comment by kaikreuzer** [comment]
Ok, so I close this PR and expect a new one at Eclipse then!

**Pull request closed without merging**
