### PR TITLE
Merge master

### PR DESCRIPTION
**Pull request by kaikreuzer**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 ok to merge?

**Comment by maggu2810** [comment]
Still no time to look at this until now.

**Comment by maggu2810** [comment]
Perhaps we should start merging every PR separately.
<code>Showing 182 changed files with 5,548 additions and 3,652 deletions.</code>
Very hard to say, if all is okay.

But what I have seen seems to be okay.

**Comment by kaikreuzer** [comment]
Well, we should hurry up making the karaf branch the master and then there'll be no need to sync anymore :-)

**Pull request merged**
