### PR TITLE
add addons directory used for fileinstall

### PR DESCRIPTION
**Pull request by maggu2810**
#415

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hm, I thought I did exactly the same, but it didn't work for me. Tested yours, and all looks good. You're the master :-)

**Comment by kaikreuzer** [comment]
I just noted that the distribution nonetheless still contains the file org.apache.felix.fileinstall-deploy.cfg. How can we get rid off it?

**Comment by maggu2810** [comment]
I know, it have not seen any problem to keep the other deploy directory (as it is using the deploy in the karaf.base directory that is moved into some subfolders).
You could configure the assembly distributions/openhab-runtime/src/main/descriptors/bin.xml to drop the configuration file and the folder.

**Comment by kaikreuzer** [comment]
Could we maybe simply rename org.apache.felix.fileinstall-addon.cfg to org.apache.felix.fileinstall-deploy.cfg?

**Comment by kaikreuzer** [comment]
It seems to work, I have changed it with https://github.com/openhab/openhab2/pull/464

**Pull request merged**
