### PR TITLE
Initial contribution of the KEBA binding, supporting the KEBA KeConta…

### PR DESCRIPTION
**Pull request by kgoderis**
…ct P20 Electrical Vehicle Charging Station

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kgoderis** [comment]
Sorry, I mistakenly pushed the wrong commit to the wrong branch, and suddenly github had closed the original pull request.

**Comment by kaikreuzer** [comment]
My comment on the other PR has not yet been addressed as it seems:

> I created a new KeBa Thing through the Paper UI. I did not configure any IP address, but still, the Thing is setting its status to "ONLINE". This should actually only be the case if there is a charging station correctly configured and accessible. Could you check?

Furthernore, if I configure an IP address that is not available, I get the following in the log:
```
2015-05-20 09:55:22 [DEBUG] [.k.handler.KeContactP20Handler:94   ] - Initializing KEBA KeContact P20 handler.
2015-05-20 09:55:22 [INFO ] [.k.handler.KeContactP20Handler:189  ] - Listening for incoming data on /0:0:0:0:0:0:0:0:7090
2015-05-20 09:55:25 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=ONLINE, getStatusDetail()=NONE, getDescription()=null]
2015-05-20 09:55:25 [DEBUG] [.c.c.r.AbstractManagedProvider:135  ] - Updated element in ManagedThingProvider.
2015-05-20 09:55:28 [DEBUG] [.k.handler.KeContactP20Handler:484  ] - Ping timed out after '3006' milliseconds
2015-05-20 09:55:28 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=OFFLINE, getStatusDetail()=COMMUNICATION_ERROR, getDescription()=Disconnecting because of a ping timeout]
2015-05-20 09:55:28 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=ONLINE, getStatusDetail()=NONE, getDescription()=null]
2015-05-20 09:55:31 [DEBUG] [.k.handler.KeContactP20Handler:484  ] - Ping timed out after '3004' milliseconds
2015-05-20 09:55:31 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=OFFLINE, getStatusDetail()=COMMUNICATION_ERROR, getDescription()=Disconnecting because of a ping timeout]
2015-05-20 09:55:31 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=ONLINE, getStatusDetail()=NONE, getDescription()=null]
2015-05-20 09:55:34 [DEBUG] [.k.handler.KeContactP20Handler:484  ] - Ping timed out after '3001' milliseconds
2015-05-20 09:55:34 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=OFFLINE, getStatusDetail()=COMMUNICATION_ERROR, getDescription()=Disconnecting because of a ping timeout]
2015-05-20 09:55:34 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=ONLINE, getStatusDetail()=NONE, getDescription()=null]
2015-05-20 09:55:38 [DEBUG] [.k.handler.KeContactP20Handler:484  ] - Ping timed out after '3005' milliseconds
```
I would expect the Thing to be set to OFFLINE with COMMUNICATION_ERROR once.

Similar stuff happens, if I use an IP address of some random device on my network (e.g. the router):
```
2015-05-20 09:58:34 [DEBUG] [.k.handler.KeContactP20Handler:94   ] - Initializing KEBA KeContact P20 handler.
2015-05-20 09:58:34 [INFO ] [.k.handler.KeContactP20Handler:189  ] - Listening for incoming data on /0:0:0:0:0:0:0:0:7090
2015-05-20 09:58:35 [DEBUG] [.k.handler.KeContactP20Handler:484  ] - Ping timed out after '3005' milliseconds
2015-05-20 09:58:35 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=OFFLINE, getStatusDetail()=COMMUNICATION_ERROR, getDescription()=Disconnecting because of a ping timeout]
2015-05-20 09:58:35 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=ONLINE, getStatusDetail()=NONE, getDescription()=null]
2015-05-20 09:58:38 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=ONLINE, getStatusDetail()=NONE, getDescription()=null]
2015-05-20 09:58:38 [DEBUG] [.c.c.r.AbstractManagedProvider:135  ] - Updated element in ManagedThingProvider.
2015-05-20 09:58:38 [DEBUG] [.k.handler.KeContactP20Handler:277  ] - An IO exception occured on channel 'sun.nio.ch.DatagramChannelImpl@2330bfd4': null
2015-05-20 09:58:38 [DEBUG] [.k.handler.KeContactP20Handler:289  ] - Disconnecting 'keba:kecontactp20:32040edf' because of a socket error
2015-05-20 09:58:38 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=OFFLINE, getStatusDetail()=COMMUNICATION_ERROR, getDescription()=Disconnecting because of a socket error]
2015-05-20 09:58:38 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=ONLINE, getStatusDetail()=NONE, getDescription()=null]
2015-05-20 09:58:40 [DEBUG] [.k.handler.KeContactP20Handler:277  ] - An IO exception occured on channel 'sun.nio.ch.DatagramChannelImpl@505819ca': null
2015-05-20 09:58:40 [DEBUG] [.k.handler.KeContactP20Handler:289  ] - Disconnecting 'keba:kecontactp20:32040edf' because of a socket error
2015-05-20 09:58:40 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=OFFLINE, getStatusDetail()=COMMUNICATION_ERROR, getDescription()=Disconnecting because of a socket error]
2015-05-20 09:58:40 [DEBUG] [.c.thing.internal.ThingManager:140  ] - Thing status of thing keba:kecontactp20:32040edf changed: StatusInfo [getStatus()=ONLINE, getStatusDetail()=NONE, getDescription()=null]
2015-05-20 09:58:42 [DEBUG] [.k.handler.KeContactP20Handler:277  ] - An IO exception occured on channel 'sun.nio.ch.DatagramChannelImpl@523586ad': null
```
Please test all these negative scenarios and make sure that the binding behaves as expected!

**Comment by kgoderis** [comment]
Well, I did check it yesterday and tested it with an "empty" IP address, not a non-allowed or existing non-keba ip address. I had to remove a line of code that caused the ONLINE/OFFLINE, but I will check your testcases tonight and modify wherever necessary

**Comment by kaikreuzer** [comment]
@kgoderis: May I ask you to create a short documentation for this binding until Sunday (May 24th)?
I have created a short guide on how to do it: https://github.com/eclipse/smarthome/blob/master/docs/sources/development/extensions/bindings/docs.md
As an example how the result could look like, please see https://github.com/eclipse/smarthome/blob/master/addons/binding/org.eclipse.smarthome.binding.hue/README.md.
Thanks!

**Comment by kaikreuzer** [comment]
Just tested your latest version. I still have a weird behavior when creating a new thing with the Paper UI and not entering any IP address:
```
2015-05-21 22:02:22 [DEBUG] [.k.handler.KeContactP20Handler:351  ] - Sending 'report 2' on the channel '/127.0.0.1:54140'->'localhost/127.0.0.1:7090'
2015-05-21 22:02:22 [DEBUG] [.k.handler.KeContactP20Handler:249  ] - Received report 2 on the listener port from /127.0.0.1:54140
2015-05-21 22:02:22 [DEBUG] [.k.handler.KeContactP20Handler:868  ] - Invalid JSON data will be ignored: 'report 2'
2015-05-21 22:02:24 [DEBUG] [.k.handler.KeContactP20Handler:351  ] - Sending 'report 3' on the channel '/127.0.0.1:54140'->'localhost/127.0.0.1:7090'
2015-05-21 22:02:24 [DEBUG] [.k.handler.KeContactP20Handler:249  ] - Received report 3 on the listener port from /127.0.0.1:54140
2015-05-21 22:02:24 [DEBUG] [.k.handler.KeContactP20Handler:868  ] - Invalid JSON data will be ignored: 'report 3'
```
I would actually expect it to not even try to contact anybody - especially not localhost... Maybe you can have another look at this. Apart from this, I think we are ready to merge. Thanks for the docu as well! Question again: Do you own the rights of the picture?

**Comment by kgoderis** [comment]
I did not test against paperui but omitting the ip in the DSL worked, unless in your case that would the equivalent of entering "" as ip addres?

**Comment by kaikreuzer** [comment]
> unless in your case that would the equivalent of entering "" as ip addres?

Probably not, because when I enter one and delete it, I have a different behavior. So I think it is a null vs. „“ in your case.

> Am 21 May 2015 um 22:28 schrieb kgoderis <notifications@github.com>:
> 
> I did not test against paperui but omitting the ip in the DSL worked, unless in your case that would the equivalent of entering "" as ip addres?
> 
> Sent from my iPhone
>

**Comment by kgoderis** [comment]
Indeed, It seems the Core is treating things differently depending on whether the Thing is created from the DSL or the UI. Omitting in the DSL yields a null for the Configuration element, in PaperUI you get an empty string. /me thinks this should be streamlined somewhere because this will come back in other bindings as well.

**Comment by kaikreuzer** [comment]
Thanks. So please remove the picture (or replace it by one that you own) and squash the commits, then I  can merge the PR.

**Comment by kaikreuzer** [comment]
Wonderful, thanks a million!

**Pull request merged**
