### PR TITLE
Network Binding: Small Fixes

### PR DESCRIPTION
**Pull request by TecSet**
- Added Generell Message when SystemPing fails
- Other Small fixes

Signed-off-by: Marc Mettke <marc.mettke@gmail.com>

### CODE REVIEW

**Comment by TecSet** [comment]
@kaikreuzer What do you think of integrating the [Http](https://github.com/openhab/openhab/wiki/Http-Binding), [NTP](https://github.com/openhab/openhab/wiki/Ntp-Binding) and [TCP](https://github.com/openhab/openhab/wiki/TCP-Binding) Binding into the Network Binding? Each of them handles a basic operation on the network and I think we don't need 4 extra Bindings for them do we?

**Comment by teichsta** [comment]
i would opt for different Bindings. At least the HTTP binding looks very different from the other protocols. What would be the advantage of aggregating different protocols into one binding?

**Comment by TecSet** [comment]
I would combine them for the same reason I would combine the [Systeminfo](https://github.com/openhab/openhab/wiki/Systeminfo-Binding) and [Exec](https://github.com/openhab/openhab/wiki/Exec-Binding) into a System Binding. 

When you want to use Homematic-Stuff you will use the Homematic-Binding. For System-Stuff you may use the System-Binding and for Network-Stuff the Network-Binding. You won't have dozent of Bindings with small functionality but everything at one place. Also non of these 4 Bindings are using background-discovery. So no performance loose by having unwanted stuff.

But I see your point in keeping them separated. When a user sees a ntp-binding he directly knows what it does. For a Network-Binding you have to read what it contains.

**Comment by kaikreuzer** [comment]
I would agree with @teichsta that HTTP and TCP bindings are something very special and they do not even fit into the new binding APIs very well - so I would prefer to simply keep them as they are in 1.x.
The NTP binding is a very dedicated use case and thus could stay on its own. I prefer to have it modular, so that people can pick and choose what they really need. If "network" is too unspecific, we should provide some good documentation in the binding overview list for it :-)

**Pull request merged**
