### PR TITLE
Add fan and battery icons.

### PR DESCRIPTION
**Pull request by reitermarkus**
https://github.com/openhab/openhab2/issues/325

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Should battery-75 really already be yellow (i.e. a kind of warning?) Would prefer a shade of green and going towards yellow on 50% only.

**Comment by kaikreuzer** [comment]
Hi @reitermarkus, I guess you didn't see my question on this PR above, so I am pinging you again :-)

**Comment by gnalbandian** [comment]
I would prefer a shade of green and after 50% yellow.

**Comment by reitermarkus** [comment]
@kaikreuzer, I saw your question. I was on vacation and the day after I got home there was a lightning strike near my house which damaged many of my appliances. So I couldn't really work on anything. =)

**Comment by kaikreuzer** [comment]
Oh oh... I hope you have a good insurance and get things replaced quickly! No worries wrt the icons, that is not urgent at all.

**Comment by reitermarkus** [comment]
I got almost everything replaced by now. Lightning strike was about two weeks ago. It's really a hassle getting everything to work again.

**Comment by reitermarkus** [comment]
You could merge this now.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
