### PR TITLE
remove GENA subscriptions on bundle stop

### PR DESCRIPTION
**Pull request by afuechsel**
Signed-off-by: Andre Fuechsel <a.fuechsel@telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This depends on https://github.com/eclipse/smarthome/pull/469.
@kgoderis, please review, if this change is ok - and directly also add it to https://github.com/eclipse/smarthome/pull/463 when you finish that PR.

**Comment by kgoderis** [comment]
Ah ok, here we have it ;-) will do

**Comment by kgoderis** [comment]
Maybe stupid question, but is there a away to do add this to ESH in an automated way? Patch and PR are not inter-project, so I presume I do a quick manual copy/paste?

**Comment by kaikreuzer** [comment]
>  is there a away to do add this to ESH in an automated way?

No, since the code is anyhow in a different namespace, so the PRs are simply not compatible.

> so I presume I do a quick manual copy/paste?

Yes, please!

**Comment by kaikreuzer** [comment]
> if this change is ok

@kgoderis, can you confirm that it is ok? Then I would merge it.

**Comment by kgoderis** [comment]
Yes it is fine

**Pull request merged**
