### PR TITLE
Add New Icons.

### PR DESCRIPTION
**Pull request by reitermarkus**
New icons: 

- Humidity (https://github.com/openhab/openhab2/issues/303)
- Playstation
- Plex
- Xbox One

### CODE REVIEW

**Comment by reitermarkus** [comment]
Should I create separate icons for `humidity_dry`, `humidity_comfort`, `humidity_wet`?

**Comment by kaikreuzer** [comment]
The -0 to -100 look good, thanks.
A question about Playstation/Xbox/Plex: Can you tell whether it is ok to use these logos and provide them under EPL here? Or are there any legal restrictions that wouldn't allow us to use them? Would be great if you could check and confirm this.

Finally, please then squash your commits and add a sign-off footer to the commit. Thanks!

**Comment by reitermarkus** [comment]
Ok, so here's what i found.

For Playstation, I think the only thing you have to do is include a trademark notice.
(http://playstation-assistenza.it/files/download/PS4%20Brand%20Guidelines_v1.0_SCEE.pdf, last page)

I think Plex should be good.
“Clearly distinguish any Plex marks, including any link to any Plex web site, from the content on your site.” (https://plex.tv/legal)

For Xbox, I only found [fansite guidelines](http://www.xbox.com/legal/fansiteguidelines).
“You may not use any of the Xbox Logos on or in connection with any unofficial products, services, or merchandise.”

**Comment by kaikreuzer** [comment]
To be honest, this all does not sound too compatible with the EPL to me, so I would prefer to leave them out (although I acknowledge that you did good work and it would be nice to have them included).

**Comment by hakan42** [comment]
But the humidity one should be ok, right?

**Comment by kaikreuzer** [comment]
Surely!

**Comment by reitermarkus** [comment]
I only added the humidity icons for now.

But out of curiosity, I would still like to know which criteria would have to be met for a third-party logo to be compatible with the EPL; does this mean the only hindrance is the license itself and not the brand policy?

**Comment by reitermarkus** [comment]
Another question: Are the `_0`, `_1` and `_up`, `_stop`, `_down` icons still used in openHAB2?

**Comment by kaikreuzer** [comment]
The _down/_stop/_up icons are only used by the Classic UI and have been moved into it already: https://github.com/eclipse/smarthome/tree/master/bundles/ui/org.eclipse.smarthome.ui.classic/web/images. So you can remove them from the icons folder.
The _0 and _1 I actually have no idea where and if they were ever used... It is fine for me to remove them as well!

**Comment by kaikreuzer** [comment]
> But out of curiosity, I would still like to know which criteria would have to be met for a third-party logo to be compatible with the EPL; does this mean the only hindrance is the license itself and not the brand policy?

IANAL, but I think it is in general simply not possible to distribute third-party logos under an open source license as it contradicts 1/6/8 of http://opensource.org/osd.

**Comment by kaikreuzer** [comment]
> I only added the humidity icons for now.

Thanks a lot!

**Comment by hakan42** [comment]
Thanks from me too, the humidity icon looks real nice :smile:

**Comment by reitermarkus** [comment]
No problem, feel free to suggest other icons if you think they should be default.

**Pull request merged**
