### PR TITLE
Implement openhab karaf wrapper

### PR DESCRIPTION
**Pull request by dvanherbergen**
#495 Implement openhab:install-service command which wraps the karaf wrapper:install.

Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Looks fine, thanks!

**Comment by maggu2810** [comment]
Just to note, that the (if I understand the commit request correctly) the openHAB runtime directory needs to be writable, now (at least runtime/karaf).

**Comment by dvanherbergen** [comment]
> the openHAB runtime directory needs to be writable

Yes, that is correct. When you install the service using openhab:install-service, this will write binaries to runtime/karaf that are used to start the service.

**Comment by kaikreuzer** [comment]
correct, but only for people wanting to use this feature.

**Comment by maggu2810** [comment]
That is not correct.
The whole data directory of Karaf is written to KARAF_BASE.
So runtime is polluted every time

**Comment by maggu2810** [comment]
Or there has been other changes I didn't noticed.

**Comment by maggu2810** [comment]
Oh, sorry, have to retest. I mixed something

**Comment by dvanherbergen** [comment]
> The whole data directory of Karaf is written to KARAF_BASE.
The data directory should still point to openhab/userdata. 
The base directory should only contain instance specific data.

**Comment by maggu2810** [comment]
Perhaps I have to less coffee.
But I tried to set on another custom Karaf distribution (with KARAF_DATA and KARAF_ETC pointing to another directory) the KARAF_BASE data read only. IMHO the lock file is written to KARAF_BASE/lock

```text
java.lang.RuntimeException: Exception instantiating lock class org.apache.karaf.main.lock.SimpleFileLock
Karaf can't startup, make sure the log file can be accessed and written by the user starting Karaf : /home/rathgeb/tmp/apache-karaf-4.0.3/BASE/lock (Permission denied)
	at org.apache.karaf.main.Main.createLock(Main.java:399)
	at org.apache.karaf.main.Main.doMonitor(Main.java:334)
	at org.apache.karaf.main.Main.access$100(Main.java:73)
	at org.apache.karaf.main.Main$1.run(Main.java:325)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.karaf.main.Main.createLock(Main.java:396)
	... 3 more
Caused by: java.lang.RuntimeException: Karaf can't startup, make sure the log file can be accessed and written by the user starting Karaf : /home/rathgeb/tmp/apache-karaf-4.0.3/BASE/lock (Permission denied)
	at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:56)
	... 8 more
Caused by: java.io.FileNotFoundException: /home/rathgeb/tmp/apache-karaf-4.0.3/BASE/lock (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:54)
	... 8 more
```

Now I can't run Karaf anymore.

@dvanherbergen Will try the openhab runtime with a read-only runtime directory and report if this also hits openHAB now.

**Comment by maggu2810** [comment]
@dvanherbergen I wanted to write: __I__ will try... and __I__ will report back...

**Comment by dvanherbergen** [comment]
> Perhaps I have to less coffee.

Maybe time for a beer :wink: ?

**Comment by dvanherbergen** [comment]
If it is just the lock file, the following may be an option:
```
karaf.lock.dir=<PathToLockFileDirectory>
```

**Comment by maggu2810** [comment]
```bash
unzip .../distributions/openhab-runtime/target/openhab-runtime-2.0.0-SNAPSHOT.zip
chmod 555 runtime/karaf/
./start.sh
```

```text
Unable to update instance pid: Unable to create directory .../runtime/karaf/instances
java.lang.RuntimeException: Exception instantiating lock class org.apache.karaf.main.lock.SimpleFileLock
Karaf can't startup, make sure the log file can be accessed and written by the user starting Karaf : /home/rathgeb/bin/pkgs/eclipse/openhab2-master/git/openhab2-karaf/_/runtime/karaf/lock (Permission denied)
	at org.apache.karaf.main.Main.createLock(Main.java:399)
	at org.apache.karaf.main.Main.doMonitor(Main.java:334)
	at org.apache.karaf.main.Main.access$100(Main.java:73)
	at org.apache.karaf.main.Main$1.run(Main.java:325)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.karaf.main.Main.createLock(Main.java:396)
	... 3 more
Caused by: java.lang.RuntimeException: Karaf can't startup, make sure the log file can be accessed and written by the user starting Karaf : .../runtime/karaf/lock (Permission denied)
	at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:56)
	... 8 more
Caused by: java.io.FileNotFoundException: .../runtime/karaf/lock (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:54)
	... 8 more
```

Will try if karaf.lock.dir is the only one.

**Comment by maggu2810** [comment]
If we change karaf.lock.dir we get a running Karaf.

But still one warning:
```text
Unable to update instance pid: Unable to create directory .../runtime/karaf/instances
```

**Comment by dvanherbergen** [comment]
What is your goal of having the runtime read-only? An alternative could be to move the karaf_base to openhab/runtime/karaf-instance. The you could set runtime/karaf as RO.

**Comment by maggu2810** [comment]
Let's ask @kaikreuzer 
But this has been the directory layout of openHAB 2 from the beginning (the difference between read-only directories and directories that will be written to).
It makes sense on Unix based systems, that not all is writable.
It is also common practice for the most software running on Unixoid systems to differ between read-only stuff that a distribution could back somewhere to /usr/ and the data that is written by execution (that is stored somewhere in home).
As I started with the Karaf migration this layout should be used.

It was also a requirement to have the option to switch the layout easily (so I introduced the set_layout file).

**Comment by kaikreuzer** [comment]
See also https://github.com/openhab/openhab2/blob/master/docs/sources/installation/runtime.md#installation-of-openhab-2

I wanted a clear separation so that it is clear what you can backup/restore/upgrade without worrying about custom changes. Furthermore as @maggu2810 says it is a common practice and many people asked for it. It was e.g. also a requirement for snappy apps (https://developer.ubuntu.com/en/snappy/build-apps/) etc. So many good reasons :-)

**Comment by dvanherbergen** [comment]
Should we then use something like
```
export KARAF_HOME="${OPENHAB_RUNTIME}/karaf-home"
export KARAF_BASE="${OPENHAB_RUNTIME}/karaf-instance"
```
where /karaf-home is read only and /karaf-instance is read write. 
Given that karaf_base/bin will be used to install the instance binaries for the service, we should prevent having those in the data folder, which could get deleted when starting with the clean option.

**Comment by kaikreuzer** [comment]
> the data folder, which could get deleted when starting with the clean option.

Does it???
I thought it would only clean the cache folder within the data folder... Otherwise we are in trouble as we are also storing mapdb files etc. in /userdata

**Comment by dvanherbergen** [comment]
karaf clean does delete the entire karaf_data folder.
Now, if it is not the goal to allow the full userdata folder to be deleted, then we could maybe do something like:
```
export KARAF_HOME="${OPENHAB_RUNTIME}/karaf"
export KARAF_DATA="${OPENHAB_USERDATA}/karaf"
export KARAF_BASE="${OPENHAB_USERDATA}/"
export KARAF_ETC="${OPENHAB_RUNTIME}/karaf/etc"
```
Then the karaf clean will only delete the subfolder and leave the instance data.

**Comment by dvanherbergen** [comment]
or maybe better:
```
export KARAF_DATA="${OPENHAB_USERDATA}/karaf-data"
export KARAF_BASE="${OPENHAB_USERDATA}/karaf-instance"
```

**Comment by maggu2810** [comment]
"karaf clean" deleted the directory Karaf writes its runtime data into (KARAF_DATA).
I previously used openhab.userdata/karaf but you liked to merge openhab.userdata and karaf_data (IIRC).
So I think it is also a matter of definition.

What should a ./start.sh clean do?
If a clean should remove all data written at runtime (so something similar to a reset), the removal of mapdb could be correct.
If we would like to remove Karaf stuff only, we have to do that.

At least we have define what we want to do.

We could also use a "clean-all", "clean-karaf", "clean-oh2" etc.

**Comment by kaikreuzer** [comment]
on the other hand: Who is using "clean" and for what purpose? If we clearly define that this will wipe all user data that could be ok.

**Comment by kaikreuzer** [comment]
> We could also use a "clean-all", "clean-karaf", "clean-oh2" etc.

Let's stay with one "clean" that is a "clean-all" then. Sorry for the confusion, @dvanherbergen.

**Comment by dvanherbergen** [comment]
OK, but what with the binaries that have been installed for starting as a service? Do we allow those to be removed too? That seems wrong to me, as after a clean openhab will no longer run as a service, without reinstalling it first.

**Comment by kaikreuzer** [comment]
That is ok for me that they are written (as a one-time effort only) to the runtime folder. This was my assumption in https://github.com/openhab/openhab2/pull/571#issuecomment-166654123.

**Comment by dvanherbergen** [comment]
I'll check if I can split the base/bin from the base/instances somehow, so that the binaries in can be kept in the runtime folder and the instance data in the userdata.

**Pull request merged**
