### PR TITLE
add pax-jetty blacklist and bump java to version 1.8

### PR DESCRIPTION
**Pull request by dvanherbergen**
- add blacklist for pax-jetty bundles #563 
- bump java to 1.8
- remove default cert from keystore

Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks!
But I would actually prefer to leave Java 7 as the minimum requirement within the bindings - there is no technical reason to require Java 8 for them.
And as these bindings are in general compatible with any ESH-based solution and ESH is still on Java 7, this change is an unnecessary constraint. Note that bindings might actually be moved as it recently happened with the Sonos binding (see https://github.com/eclipse/smarthome/pull/548).

**Comment by dvanherbergen** [comment]
I've limited the PR to :
- java version bump for compilation and build/launch. 
- keystore cert removal
- fix for duplicate jetty.xml 

I've also removed the blacklist, I will check pax-web 4.2.4. first.

**Comment by kaikreuzer** [comment]
Thanks!

**Comment by maggu2810** [comment]
You think about the problems using 1.7 runtime and 1.8 compiled classes?

**Comment by maggu2810** [comment]
Ah, ok, 1.8 is now a requirement to execute the OH2 runtime. Missed that

**Pull request merged**
