### PR TITLE
Enphase Energy binding reported by xsnrg in the forums to be compatible

### PR DESCRIPTION
**Pull request by hakan42**
https://community.openhab.org/t/enphase-energy-binding-works/4145

### CODE REVIEW

**Comment by hakan42** [comment]
@teichsta , @kaikreuzer , could you please merge this?

**Comment by kaikreuzer** [comment]
Yes, thanks, but I will also add it to the distribution at the same time!

**Comment by hakan42** [comment]
ah, o.k., forgot that last part as I am picking my OH1 addons from the 1.8.0 jenkins archive by hand (script, actually) :smiling_imp:

**Comment by xsnrg** [comment]
@hakan42  something like this:  https://github.com/xsnrg/OpenHAB2-tools ?

 :-)

**Comment by kaikreuzer** [comment]
Naaa, it will be so much nicer once @maggu2810 and I have finished https://github.com/openhab/openhab2/issues/194 - stay tuned :-)

**Comment by xsnrg** [comment]
@kaikreuzer No doubt!  I have been watching that thread closely.

**Comment by hakan42** [comment]
What exactly would be "Mit den Hufen scharren" in english? Whatever it is, it is what I'm doing :smiling_imp:

**Comment by kaikreuzer** [comment]
Maybe "waiting for christmas" ;-) That's about how long you should have to wait maximal. But you know "Vorfreude ist die schönste Freude" 8-)

**Comment by xsnrg** [comment]
Hmm, mein Deutsch is a little rusty, but hoof scraping must be a German colloquialism.  Kind of like waiting with baited breath.  What does that mean exactly?  One ate the fishing lure?

**Comment by kaikreuzer** [comment]
Superseded by https://github.com/openhab/openhab2/pull/483.

**Pull request closed without merging**
