### PR TITLE
Network binding time extension

### PR DESCRIPTION
**Pull request by FallenRiteMonk**
I tried my self in extending the network to be able to display the time it takes to ping a device on the network.
I would like @TecSet to test and verify that this is not breaking any of his functionality.

P.S.: This has been poorly tested due to the my current residence. Please don't merge until somebody can validate the functionality!

### CODE REVIEW

**Comment by TecSet** [comment]
The Code LGTM - Will test it as soon as possible

Nice work so far @FallenRiteMonk

**Comment by TecSet** [comment]
@FallenRiteMonk  There are 2 Errors in your Code:

1. Raw Type does not have a String Parameter:

>```java
State state = new RawType("" + networkService.updateDeviceState());
```

```java
State state = RawType.valueOf("" + networkService.updateDeviceState());
```

2. You don't update the time at the automaticRefresh

>```java
public void newState(boolean state) {
    State newState = state ? OnOffType.ON : OnOffType.OFF;
    updateState(CHANNEL_ONLINE, newState);        
}
```

```java
public void newState(long state) {
    State onlineState = state < 0 ? OnOffType.OFF : OnOffType.ON;
    State timeState = RawType.valueOf("" + state);
    updateState(CHANNEL_ONLINE, onlineState);
    updateState(CHANNEL_TIME, timeState);
}
```

Will further test your update when the Error's are fixed

**Comment by FallenRiteMonk** [comment]
Fixed. Please test again

**Comment by TecSet** [comment]
@FallenRiteMonk Another Fix needed:
The StateUpdate Interface needs a fix for the new parameter

>``` javascript
public void newState(boolean state);
```
``` javascript
public void newState(long state);
```

**Comment by FallenRiteMonk** [comment]
Ok try again please.

**Comment by FallenRiteMonk** [comment]
@TecSet have you tested it again? Is everything fine?
If so please let me know so i can rebase the commits to be merged!

**Comment by TecSet** [comment]
Sry @FallenRiteMonk, have been too busy yesterday to further test your code

But anyway, I found further bugs:

1. In your channel, you do use Number as type, but in your Java Code you use the RawType. You have to use DecimalType to Display Numbers.

>```xml
<channel-type id="time">
        <item-type>Number</item-type>
        ....
</channel-type>
```

>```java
State state = RawType.valueOf("" + networkService.updateDeviceState());
```

```java
State state = new DecimalType(networkService.updateDeviceState());
```

2. With the upper configuration, the item will always be set to 1 or 0, even though updateDeviceState returns Values like 5025. Thats strange and needs further investigation.

```java
State state = new DecimalType(networkService.updateDeviceState()); // Returns 5025 but Value of DecimalType is 0 or 1
```

3. currentTimeMillis() on MAC does return nanoseconds (read JavaDoc). Thats a problem which may need System Based Programming. Further Investigation necessary.

```java
System.currentTimeMillis();
```

Unfortunately I don't have time to fix those, currently, but I'm happy to review your code again.

**Comment by FallenRiteMonk** [comment]
I see the point of switching to DecimalType and did that. Also replaced currentTimeMillis with nanoTime, which should solve the MAC problem.
Should I leave the time in nanos and update the docs or should I do a conversion to millis? whats your opinion?
Couldn't do anything about the DecimalType resolting in 0 or 1 problem since I still have no test environment, but couldn't this also be a problem with DecimalType?
where do you see that the value is 0/1? In the logs or in the GUI? Do you use DecimalType.longValue()?

**Comment by TecSet** [comment]
> Should I leave the time in nanos and update the docs or should I do a conversion to millis? whats your opinion?

I'd prefer millis, because nano is not accurate enough and ping also uses milis.

> where do you see that the value is 0/1?

I use the Paper UI (Browser UI for OpenHab which is  delivered with the runtime)

> Do you use DecimalType.longValue()?

OpenHab does it itself, have no influence

> but couldn't this also be a problem with DecimalType?

I'm not sure, but it might me. I'll test it.

**Comment by FallenRiteMonk** [comment]
Would you please try outputting the the value to the log using DecimalType.longValue() and check if the value there is as it should, just to see if the error is in my code or somewhere else!
As far as I can imagine the error could be in DecimalType (which I doubt), in the way it gets formatted, or generally in the Paper UI (which is pretty new and still under development).
Therefor if the log would output the correct value then the code could be merged and the error has to be somewhere else!

**Comment by TecSet** [comment]
Sry, now I know why it has always been 1 or 0. We were using milliseconds and it takes between 0,4 and 1,2 miliseconds to reach the device. So the state is 0 or 1 ... 

Okay this is the last fix and then we're good to go:

Change return value from long to double (for Values like 1.8 ms)

```java
private static double updateDeviceState() {
    (...)
}

private static double updateDeviceState(...) {
    (...)
    return success ? pingTime / 1000000.0f : -1;
}

public interface StateUpdate {
    public void newState(double state);
    public void invalidConfig();
}

public void newState(double state) {
    (....)
}
```

**Comment by FallenRiteMonk** [comment]
Okay then please check one last time and then mark somebody who can merge!

Thanks very much,
FallenRiteMonk

**Comment by TecSet** [comment]
@kaikreuzer LGTM - ready to be merged

**Comment by kaikreuzer** [comment]
Thanks for the review @TecSet.
@FallenRiteMonk, could you pleas squash your commits and make sure that the resulting commit is signed-off (see https://github.com/openhab/openhab2/blob/master/CONTRIBUTING.md#sign-your-work). Thanks!

**Comment by FallenRiteMonk** [comment]
Signed-off-by: Florian Klement <fallenritemonk@gmail.com> (github: FallenRiteMonk)

**Comment by kaikreuzer** [comment]
Thanks again :-)

**Pull request merged**
