### PR TITLE
Remove tar.gz distribution

### PR DESCRIPTION
**Pull request by dvanherbergen**
Removed tar.gz distribution #515 
Merged openhab-runtime and openhab-runtime-karaf into single zip distribution.

Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
One comment: @maggu2810 explicitly renamed distribution to distributions, because he said that we might have different distributions in the future, like one for the minimal runtime, one for the standard, one for offline installation and one for online, etc. So I guess he would prefer if you change the name of the folder back :-)

**Comment by dvanherbergen** [comment]
Renamed back to distributions...

**Comment by maggu2810** [comment]
Will have a look at this later. Thank you...

**Comment by maggu2810** [comment]
I have a look at the Github "Files changed" view and it seems to look good. IMHO there is no need to further inspect this on my machine. I am trust @dvanherbergen that he already has done some tests and if we run in some trouble we could fix it later.

@dvanherbergen :+1: :wink:

**Comment by dvanherbergen** [comment]
Yes, I did test it and I even checked for unwanted whitespace in the XML ;-)

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
