### PR TITLE
verifying features

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This is a try to implement https://github.com/openhab/openhab2/issues/386.
Unfortunately, I get verification failures with
```
[WARNING] Unable to resolve framework features
```
@maggu2810 Any idea, what I might have done wrong?

**Comment by maggu2810** [comment]
I will try to have a look at this. Don't have much time ATM.

**Comment by kaikreuzer** [comment]
@cschneider, if you have any insights, please let us know :-)

**Comment by maggu2810** [comment]
This is a little bit complicated...

First, you are missing the descriptor containing the framework feature
```xml
<descriptor>mvn:org.apache.karaf.features/framework/${karaf.features.version}/xml/features</descriptor>
```

Next, we also need the feature, that does contain all the openhab-runtime features
```xml
<descriptor>mvn:${project.groupId}/org.openhab.feature.runtime/${project.version}/xml/features</descriptor>
```
because they are used as dependent feature.

Another problem we could run into:
The Xtext stuff etc. does not work using a non-Equinox OSGi framework, so to resolve them with a non-Equinox OSGi framework (Felix) will not work (does not know, how the resolve work / could be configured).

But if you add that two dependencies, you will see, that the verify process is started.

**Comment by maggu2810** [comment]
Next step (as I already expected):

```text
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-tp-base; type=karaf.feature; version=0 [caused by: Unable to resolve openhab-tp-base/2.0.0.SNAPSHOT: missing requirement [openhab-tp-base/2.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.eclipse.core.runtime; type=osgi.bundle; version="[3.10.0.v20140318-2214,3.10.0.v20140318-2214]"; resolution:=mandatory [caused by: Unable to resolve org.eclipse.core.runtime/3.10.0.v20140318-2214: missing requirement [org.eclipse.core.runtime/3.10.0.v20140318-2214] osgi.wiring.bundle; osgi.wiring.bundle=org.eclipse.osgi; bundle-version="[3.7.0,4.0.0)"; visibility:=reexport; filter:="(&(osgi.wiring.bundle=org.eclipse.osgi)(bundle-version>=3.7.0)(!(bundle-version>=4.0.0)))"]]
```

**Pull request closed without merging**
