### PR TITLE
updated to Swagger UI 2.0

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
After this one is merged, we should merge it to branch "karaf" and add the related feature for jax-rs swagger bundles.

**Comment by kaikreuzer** [comment]
That's actually what I tried to do, but then I found https://github.com/hstaudacher/osgi-jax-rs-connector/issues/124. Holger missed to upload the provider.swagger jar to Maven Central and thus we cannot use the Karaf feature :-(

**Comment by maggu2810** [comment]
The jar and pom are available, so don't know, why he do not like to upload it now.
So, we have to solve this the same way as all the other dependencies we have, using another maven repo...

**Comment by kaikreuzer** [comment]
Yes, unfortunately. Btw, how did you create your temporary Maven repo with the bundles of the TP?
Risking to sound foolish by repeating an old discussion: Couldn't we use https://github.com/hstaudacher/tycho-karaf-bridge to easily do this within the build itself?

**Comment by maggu2810** [comment]
> Btw, how did you create your temporary Maven repo with the bundles of the TP?

I have used maven and the "deploy:deploy-file" goal.
https://maven.apache.org/guides/mini/guide-3rd-party-jars-remote.html

> Couldn't we use https://github.com/hstaudacher/tycho-karaf-bridge to easily do this within the build itself?

I read the page correctly ("The kar-packager is a small Maven Plugin to create Apache Karaf Archives (.kar) from a given folder.") you still need the jar files placed in a directory at build time.
Would you like to add them to the git repository of OH2? Or do you want to convert a p2 repo?

**Comment by maggu2810** [comment]
Do we need the gson and the swagger provider now, or can we get rid of the gson one?
I am not familiar with all that jax-rs stuff.

**Comment by kaikreuzer** [comment]
These are two completely different things:
gson is used by Jersey to (de)serialize the JSON on the REST API.
swagger is only required for assembling the swagger.json file for the Swagger UI (only required if the rest-docs feature is installed)

**Comment by maggu2810** [comment]
Ok, I created a swagger provider feature and added the one missing jar to the temp. repo.

**Pull request merged**
