### PR TITLE
New Icon Set

### PR DESCRIPTION
**Pull request by reitermarkus**
I have been working on these for quite a while now, and now I have finally finished all icons.

I hope you all like them.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Markus,

Sorry for having kept you waiting - you really did a tremendous job here, it must have been a huge effort to create all these svg versions from scratch!
For a test, I have today changed the Classic UI to use SVG instead of PNG and this actually also worked perfectly - so at least for this UI I would consider to completely switch over. For the native apps, we will have to stay with PNG for the moment though.
I wonder, if you were ok with contributing these icons directly to Eclipse SmartHome instead of openHAB 2? With respect to https://bugs.eclipse.org/bugs/show_bug.cgi?id=423545, I would actually like to package your icons as one icon set for ESH. If you like this idea, give me a few days and I will come up with a suggestion for the structure on how to do this. I'd also then directly improve the iconservlet to serve the SVG versions to the ClassicUI.

Regards,
Kai

**Comment by kaikreuzer** [comment]
Sleeping over it, I think I'd suggest to do it in two steps - merge this PR right now and then work on moving it to ESH as an icon set.
May I hence ask you to squash the commits of this PR into a single one? Please also make sure that this one single commit is then signed off (see https://github.com/openhab/openhab2/blob/master/CONTRIBUTING.md#sign-your-work). Thanks!

**Comment by CWempe** [comment]
As I mentieoned in the google group:

I think the women_*.png's are calculated incorrectly.
https://github.com/reitermarkus/openhab2/blob/master/distribution/openhabhome/runtime/icons/woman_5.png

The figure appears only in the left top corner of the png.
Same goes for man_*.png

I am not sure if there icons are contained in this specific merge, because I cannot find them above.

**Comment by reitermarkus** [comment]
Thanks for noticing, I will fix these.

Also, should we remove the duplicate images like garden2 and garden3? Do we need backward compatibility for icons?

**Comment by kaikreuzer** [comment]
> Do we need backward compatibility for icons?

Good question. I think your approach to provide a script for duplicating icons is a neat idea. So I would not keep the duplicate icons, but to provide the script that people can execute if they want to have backward compatibility with existing sitemaps.

**Comment by reitermarkus** [comment]
I'm seeing a problem now with the parents icons. The filename range from `parents_1_1` to `_6_6`, so the `parents-off` icon wouldn't automatically be assigned.

Also, what to do about other duplicates, e. g. the `garagedoor-open` and `garagedoor-0` icon?

**Comment by reitermarkus** [comment]
Ok, I added a `text` icon. You can merge this now, unless you have a suggestion for those other duplicates.

**Comment by kaikreuzer** [comment]
> The filename range from parents_1_1 to _6_6, so the parents-off icon wouldn't automatically be assigned.

Why are there actually so many? I was so far only aware of the on/off versions. What is the meaning of the _x_y?

> Also, what to do about other duplicates, e. g. the garagedoor-open/garagedoor-0, heating-off/heating-0 icon?

For the moment, we should have them all available, I guess.

> By the way, should the text icon you added recently stay empty or resemble a page with text?

It was added as it is used as a default for text widgets without an individual icon reference, so the empty version was alright (just not to show a broken link image). But your new text icon looks nice, we can for sure keep it.

**Comment by reitermarkus** [comment]
There are so many because I created 6 different skin tones according to the “Fitzpatrick Scale”.

If there's nothing else, we can merge this now.

**Comment by kaikreuzer** [comment]
Thanks for this amazing work!

**Comment by LeDumpier** [comment]
Hi all,

Would anyone have a 'for dummies' reference on how to use these Icons? I.e. how do we download the set? 

And for OpenHAB2 should I only use the .svg type icons?

Many thanks in advance

**Comment by udo1toni** [comment]
These icons are on board if installing OH2, to use an icon, just set it through item definition by using `<itemname>` after label definition. be aware that no extension is allowed! OH2 decides itself, if using svg or png - this is configured through paper UI.

**Comment by potyt** [comment]
A few suggestions to icons I thought I'd find and couldn't:

- Mobile phone
- Computer
- Printer
- Fridge
- Shower (room)
- Underfloor heating

They're all common in homes, the devices are all networked (even fridges!) and all can be usefully included in a home automation system like openhab.

**Comment by potyt** [comment]
A few more that came to mind:
- Light meter
- Carbon monoxide monitor

**Pull request merged**
