### PR TITLE
Network Binding Handler dispose fix

### PR DESCRIPTION
**Pull request by FallenRiteMonk**
Hy @TecSet,

could you please approve this, since it seemed to be wrong in my point of view!

Thanks and Greetings,
FallenRiteMonk

### CODE REVIEW

**Comment by TecSet** [comment]
@kaikreuzer LGTM, fix is correct and can be merged

**Comment by kaikreuzer** [comment]
@FallenRiteMonk Please sign-off your commit, thanks!

**Comment by FallenRiteMonk** [comment]
Signed-off-by: Florian Klement <fallenritemonk@gmail.com> (github: FallenRiteMonk)

**Comment by kaikreuzer** [comment]
Perfect, thanks!

**Pull request merged**
