### PR TITLE
Honeywell WiFi binding

### PR DESCRIPTION
**Pull request by Rendman**
Recreated this PR, due to last minute critical bugs I noticed. (and you would have too!)

For issue #333

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks!

> Recreated this PR, due to last minute critical bugs I noticed

Note that you can at any time add further commits to your branch - they automatically end up in this PR, so no need to recreate it.

**Comment by Rendman** [comment]
I'm having problems with EGit in Eclipse, so I recreated the repo. I know this probably caused some problems.

**Comment by kaikreuzer** [comment]
No problem, just wanted to mention that it is not necessary to create new PRs. I don't mind if there are old ones being closed either.

**Comment by Rendman** [comment]
Kai, this page is now saying that the merge is coming from an unknown repository. Is there anything I need to do to fix that, or is it good?

**Comment by kaikreuzer** [comment]
You are right, this is most likely a problem, because you wouldn't be able to do any further updates to it (like squashing commits when the review is done). So better create a new PR from your existing fork.

**Comment by jeremeguenther** [comment]
Hi Kai,  I am brand new to openhab and would like to start using it.  I noticed this honeywell wifi binding is no longer included in the master repository.  Is there a reason it was excluded?  I was hoping to use it for my wifi honeywell.

**Comment by kaikreuzer** [comment]
The current PR of @Rendman is here: https://github.com/openhab/openhab2/pull/339
@jeremeguenther: If you are brand new, I would suggest to start with openHAB 1, since openHAB 2 is currently under development and only meant for developers who are familiar with openHAB 1 already.

**Comment by jeremeguenther** [comment]
Thanks @kaikreuzer I have gotten openhab up and running with a basic MODBUS module, and am next hoping to find a way for an HNAP device.  I am looking forward to version 2 for new features, I would love to help with it, but doubt I will be familiar enough with the system for at least another year.

**Pull request closed without merging**
