### PR TITLE
Fixed build breaking artifact id of CalDAV binding

### PR DESCRIPTION
**Pull request by hakan42**
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks!

**Comment by querdenker2k** [comment]
why are the cfg files outside the services folder?

**Comment by hakan42** [comment]
Another mistake on my part, I guess. I have the same error with sapp.cfg

I promise not to create any more PRs with too little sleep :smile:

**Comment by hakan42** [comment]
Created PR #512 to move the files to their proper locations. Sorry again :blush:

**Pull request merged**
