### PR TITLE
Bugfix multiline messages

### PR DESCRIPTION
**Pull request by habnefrage**
As promised (https://github.com/openhab/openhab/pull/2448), I added my bugfix into OH2 aswell.

Please have a look at my changes.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@marcelrv, could you please review this PR? Thanks!

**Comment by kaikreuzer** [comment]
@habnefrage What I notice is that your new classes are lacking the license header. Please check https://github.com/eclipse/smarthome/blob/master/docs/sources/development/guidelines.md for some formal code style guidelines - thanks!

**Comment by habnefrage** [comment]
@kaikreuzer I ran this mvn license:format command. There are lots of files changed now. I assume, I should only commit files changed by me, not the other one, correct?

**Comment by kaikreuzer** [comment]
Yes, please, only your changes. I will clean up the rest soon.
Please also run it with -Dyear=2015 parameter otherwise it puts 2014-2014 in the header (I will also change the default soon).

**Comment by marcelrv** [comment]
@kaikreuzer yes sure. We'll first finish the OH1 version then the OH2 one,

@habnefrage 
Hi Christian, any idea why github seems so many changes.e.g. in the MaxCubeBridgeHandler.java
and the mysterious (non)change in project-orga/CONTRIBUTING.md

**Comment by habnefrage** [comment]
Hi Marcel,
I thing it is because oft the formatter. I used the one that was linked on
the page kai asked me to incorporated.
After importing the formatter rules i reformatted the code. Sorry for that!

Actually i only chengef the code along the two occurences of
reader.deadline() Command. And i removed the function processRawMessage
that returned the correct message type.
Am 16.04.2015 4:19 vorm. schrieb "Marcel" <notifications@github.com>:

**Comment by kaikreuzer** [comment]
If this is done and ready to be merged, may I ask you to squash your commits into a single one (see end of the paragraph of https://github.com/openhab/openhab2/blob/master/CONTRIBUTING.md#conventions)? Thanks!

**Comment by marcelrv** [comment]
Hi @habnefrage 
when you squash your commits, please also reset the unchanged files that now have lot of changes due to the reformatting 
CONTRIBUTING.md , MessageType.java, Message.java

possibly also reset and add again the 5-6 lines in MaxCubeBridgeHandler.java so it does not get market as all changed

**Comment by marcelrv** [comment]
@habnefrage,
In the meantime there were few chances in maxcubebridgehandler, from the
error it seems like git could not automatically merge it.

That sometimes happens and then you need to manually merge it. Can do that
by using merge in eclipse or (sometimes easier) replace the file with the
latest and reapply

**Comment by habnefrage** [comment]
OK, I merged my changes with last version from upstream.
I hope it's all OK now.

**Comment by kaikreuzer** [comment]
Hm, there are still merge conflicts on the class MaxCubeBridgeHandler. Could you please check that you are really basing upon its latest revision?

**Comment by marcelrv** [comment]
Looks like maxcubebridgehandler is the latest revision, but fine without the rebase, as it also sees my chances as change

**Comment by habnefrage** [comment]
GIT is driving me crazy...
Let me retry tonight :-)
Am 26.04.2015 10:51 nachm. schrieb "Marcel" <notifications@github.com>:

**Comment by kaikreuzer** [comment]
> Let me retry tonight :-)

Any success?

**Comment by kaikreuzer** [comment]
@marcelrv, Do you want to take over and create a PR for it?

**Comment by marcelrv** [comment]
@kaikreuzer, yes maybe that's easier.

**Comment by kaikreuzer** [comment]
Superseeded by https://github.com/openhab/openhab2/pull/228

**Pull request closed without merging**
