### PR TITLE
MAX! Update for new xsd definitions

### PR DESCRIPTION
**Pull request by marcelrv**
Also includes:
Set boost needs a setpoint temperature #1821
(https://github.com/openhab/openhab/pull/1821) alternative approach
simplifying the code, eliminating the need for PR #82

new lines at end of all files as suggested by Thomas.

Signed-off-by: marcel <marcel@verpaalen.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Great, nice to see the XML extensions being used so quickly!
There is just one thing I wonder: Whether it makes sense to have the "max" tag on the channels - what is the idea behind it?
I know we are lacking any kind of guideline on how tags should be used (and we will also have to come up with some default tag library) - so no offence at all.

**Comment by marcelrv** [comment]
Well,

The thinking behind it was that it would be nice to have all the items
related to the max system in one screen. Hence the max tag.
I made all the regular heating stuff  (mode, set temp and actual temp) as
heating reflecting the basic items for the heating system.

I assume we will later in the UI be able to group stuff by the tag

Also I want to see if I can dynamically add tags later onwards, as I would
like to tag with the room names (coming from the max cube definitions) as
well.


2015-01-07 23:08 GMT+01:00 Kai Kreuzer <notifications@github.com>:

**Comment by kaikreuzer** [comment]
> The thinking behind it was that it would be nice to have all the items
related to the max system in one screen. Hence the max tag.

Hm, if this would be a best practice", we could actually adapt the thing infrastructure to add such tags automatically for items - so even in this case there is no need to have them specified here. I would therefore suggest to remove them!

**Comment by kaikreuzer** [comment]
Besides this, this PR is ready for merging.

**Comment by marcelrv** [comment]
Okay removed the max tag.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
