### PR TITLE
Remove classpath reference to jars which are embedded during build.

### PR DESCRIPTION
**Pull request by dvanherbergen**
#557 Removed unneeded references

### CODE REVIEW

**Comment by dvanherbergen** [comment]
don't merge this one just yet. still testing the build..

**Comment by dvanherbergen** [comment]
I forgot that manifest first builds are never easy...
It's tested and good to go now.

**Comment by kaikreuzer** [comment]
Indeed tricky - thanks!
Could you please squash your commits before the merge?

**Comment by dvanherbergen** [comment]
done.

**Comment by kaikreuzer** [comment]
Thx.

**Pull request merged**
