### PR TITLE
reimplemented add-on management using the ESH ExtensionService interface

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
I have to merge this PR locally and check the whole implementation...
Review this PR alone does not it a little bit difficult (e.g. why we need the FeatureInstaller and the KarafExtensionService -- it seems that the extension service already using the feature service of Karaf to install a feature / extension).

**Comment by maggu2810** [comment]
Shouldn't we drop the FeatureInstaller and change the DS to use the KarafExtensionService?

**Comment by kaikreuzer** [comment]
Note that this is just an adjustment of my implementation in https://github.com/maggu2810/openhab2/pull/2, since I have introduced the general concept of extension management in ESH.

The FeatureInstaller takes care of the addons.cfg file, which is OH2 only. The ExtensionService is the new ESH concept for the REST API. I therefore didn't touch the FeatureInstaller in this PR (besides of some simply renamings).

**Comment by maggu2810** [comment]
ok

**Comment by maggu2810** [comment]
I don't remember the addons.cfg... ;)

**Comment by maggu2810** [comment]
But you missed the DS for the KarafExtensionsService. Didn't you?

**Comment by kaikreuzer** [comment]
You are absolutely right - I missed adding this file. Added it now!

**Comment by kaikreuzer** [comment]
Ok to merge now?

**Comment by maggu2810** [comment]
Why do you remove the file "featureresource.xml". I assume it should be kept for the addons.cfg

**Comment by kaikreuzer** [comment]
No, the addons.cfg has nothing to do with the REST API. And the FeatureResource is not required anymore, since ESH now has the REST resource: https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.core/OSGI-INF/extensionresource.xml

**Comment by maggu2810** [comment]
LGTM

**Pull request merged**
