### PR TITLE
added projects for OH1 and ESH development to the Oomph profile

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Could we using the same working set names prefix in all the three projects?
* "2.x Core Bundles" could be named "OH2 Core Bundles" (OH2 Core Bundles already exists)
* "1.x Core Bundles" could be named "OH1 Core Bundles"
* Features, Addons could be prefixed with OH2

It is correct that "Bundles" contains all bundles?

**Comment by kaikreuzer** [comment]
@maggu2810, done with https://github.com/openhab/openhab2/commit/1d696750a89118e559e7eb8972eb8206a0b8da4c.

**Comment by maggu2810** [comment]
Thanks

**Comment by maggu2810** [comment]
* I installed all three projects at once.
* The working set "OH1 Addons" contains "org.openhab.action.astro".
* The astro binding is missing.

The astro action uses
```java
import org.openhab.binding.astro.internal.calc.SunCalc;
import org.openhab.binding.astro.internal.model.Sun;
```

This imports cannot be resovled.

**Comment by maggu2810** [comment]
The action org.openhab.action.openwebif uses
```java
import org.openhab.io.net.actions.Ping;
```

and "Require-Bundle: org.openhab.io.net"

Should we create a issue on OH1 that this require bundle should be changed to import package?

**Comment by kaikreuzer** [comment]
Yes, there are clearly compilation problems and other incompatibiities. I created that profile to make it easy for OH1 developers to help on testing and fixing these things (will announce the profile soon on https://community.openhab.org/t/we-need-your-help-on-testing/298?u=kai). So everything that is related to OH1 should be entered as an issue there (or fixed right away).

> The working set "OH1 Addons" contains "org.openhab.action.astro".

I will remove it, since there is an OH2 Astro binding.

**Pull request merged**
