### PR TITLE
Karaf Container for openHAB2

### PR DESCRIPTION
**Pull request by maggu2810**
The topic is already discussed here: #194 

I think the current state needs further testing by the community but should be in a state to start with testing.
Some directories changed their name, some are not available anymore - merging is time consuming. I would prefer to do the further work upstream on the main project.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Cool, thanks! I will try it out over the weekend!

**Comment by kaikreuzer** [comment]
Thanks @maggu2810, I have just tried it out.
You have done a tremendous work here! The build was successful and I was directly able to start things up - you even have created single features for all addons already, very cool!

I stumbled across a few small problems and things that should be improved before we could use it as a replacement for the current distribution; I would suggest that we could merge it already as a branch into the main repo, have a nightly build set up for it, have people test it and use the standard issue tracker for all changes.

But before doing this, I would need some a solution for a blocking issue: I noticed that the bundles that you have changed from Tycho to Maven Bundle Plugin (i.e. core and io.myopenhab), that they do not appear on the "Plug-ins" tab in the launch configuration; which means that I have no way to start up openHAB from within the IDE. How do you do that?

**Comment by maggu2810** [comment]
After I built them once (using the Eclipse IDE), they are available on my system.
Have to check if you have to use Maven install run target or the normal build.
Could you check clean & build in Eclipse?
But it should work to use them in the Eclipse IDE, I tested it.

Do not know if you already tried debugging, but you can start karaf with the argument debug and be able to use remote debugging over a socket connection (port 5005).

**Comment by kaikreuzer** [comment]
> After I built them once (using the Eclipse IDE), they are available on my system.

I hope we find a solution that this is not necessary - it would be a huge step backward from the current use of the IDE and its ease of set up.

> Could you check clean & build in Eclipse?

The problem is that there is no MANIFEST.MF on these bundles and thus PDE does not recognize and consider them. Do I need any special Eclipse plugin to have that automatically generated?

> Do not know if you already tried debugging, but you can start karaf with the argument debug and be able to use remote debugging over a socket connection (port 5005).

Remote debugging is no replacement for running the code from within the IDE directly...

**Comment by maggu2810** [comment]
> I hope we find a solution that this is not necessary

Sure, would be good to find one.

> Do I need any special Eclipse plugin to have that automatically generated?

Will check what I have done (tomorrow) and report.

> Remote debugging is no replacement for running the code from within the IDE directly...

That was not my intention.
I just want to state that and I do not know how familiar you are with Karaf already.
 Perhaps the context of my note was a little bit confusing.

For the Eclipse integration themselves:
* http://karaf.922171.n3.nabble.com/Eik-upgrade-td4042358.html
* http://karaf.922171.n3.nabble.com/EIK-Karaf-4-support-on-Eclipse-Mars-td4042052.html

**Comment by meisterfuu** [comment]
One time we developed a project for/with karaf at work. I will have a look how our workflow was.

**Comment by kaikreuzer** [comment]
Googling a bit, I doubt that there'll be any easy solution to mix Tycho and MBP projects within a launch config; after all, Tycho bundles require the target platform, so all dependencies have to be available there.
The only other good technology to launch a whole OSGi application from within Eclipse seems to be BNDTools, but you weren't fond of them.
I think I would prefer to stay with Tycho bundles; does this really mean much overhead for the maintenance? All we would need to do is to also maintain a Karaf feature, which is in sync with the target platform, correct? Or am I missing something crucial? We could potentially manage the target platform based on pom dependencies like described in https://vzurczak.wordpress.com/2013/02/27/a-target-platform-based-on-apache-felix/. Would that help?

**Comment by kaikreuzer** [comment]
What might be worth a try is http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#eclipsepde-integration - if m2e can automatically trigger this generation and there is no manual maven build necessary for it.

**Comment by maggu2810** [comment]
Perhaps we should change the two bindings to use Tycho again (revert the changes in the binding, but kept the mechanism using the different parent poms) until we have a solution for the IDE.

**Comment by maggu2810** [comment]
I would prefer to help development the project EIK to get a Karaf integration for Eclipse instead of adding hacks to the POMs etc.

**Comment by kaikreuzer** [comment]
> Perhaps we should change the two bindings to use Tycho again (revert the changes in the binding, but kept the mechanism using the different parent poms) until we have a solution for the IDE.

Agreed. Let me know when you have reverted it, I'll then have another look the PR.

**Comment by maggu2810** [comment]
> Let me know when you have reverted it

Done, changes are reverted. Squash will after review, so we could see what is done in the different iterations.

> But before doing this, I would need some a solution for a blocking issue

Is the blocking issue resolved?

> I stumbled across a few small problems and things that should be improved
> and use the standard issue tracker for all changes.

Okay, let's create a issue tag for the Karaf part.

**Comment by kaikreuzer** [comment]
> Is the blocking issue resolved?

Yes, I hope so. Will review tonight and give you feedback, thanks!

**Comment by kaikreuzer** [comment]
Ok, with https://github.com/maggu2810/openhab2/pull/1, the blocker is solved - it is possible to start up everything within the IDE.

It seems to work pretty well - so my main wish would be to make the distribution a bit similar to the current one, so that we really end up with an openHAB distribution and not a Karaf distribution containing openHAB, see what I mean?

I would love if we could get a zip that has the same folders as the current download, i.e. mainly "conf", "runtime", "userdata", "addons" and some start scripts. I think this could be done by repackaging the Karaf distro like I started in https://github.com/kaikreuzer/openhab2/tree/karaf/distribution/downloads.
In details this should:
- have the files in the root of the zip, i.e. not package them within a folder of the file name
- have Karaf within the runtime folder
- have start.sh/bat scripts that simply call runtime/bin/karaf
- configure KARAF_BASE to ${openhab.home}/runtime
- configure KARAF_DATA to use ${openhab.home}/userdata
- configure logging to log to /userdata/log/openhab.log
- configure felix.fileinstall to read bundles from ${openhab.home}/addons

These changes would make the zip as backward compatible as possible. I am thinking of the many scripts and tools that people have built (like puppet scripts, docker containers, etc.) that otherwise would completely break.

Furthermore, I think we should completely remove the (old) openhab2-demo distribution project and rather move these files into a demo-feature that can be installed. This should be possible, right?

**Comment by maggu2810** [comment]
> configure felix.fileinstall to read bundles from ${openhab.home}/addons

You already named the variables that karaf is using. Just to keep it tracked: For standard Karaf the deploy directory does handle this topic.

**Comment by kaikreuzer** [comment]
So do you agree with my suggestion? Do you see any obstacles? What would be required to change in the Karaf distro for it? I guess we mainly would need to configure the folders in setenv, right?
What I missed to mention: All files that Karaf needs write access for should be within userdata (I think this is the case with just a few exceptions like "lock" already). The only exception to this rule should be the conf folder when installing features.

**Comment by maggu2810** [comment]
The lock, instance and data are created if you start from a clean one.

If you want to support existing scripts you need probably / surely a similar directory layout.
For me I need to know what is the runtime data (e.g. the current directory data for Karaf and userdata for OH2). I do not need the same layout as before for myself. I would prefer to kept as much as upstream as possible. But as stated before, I can rewrite my scripts and do not need to grant backward compatibility.

So, for OH2 you decided to kept it.
Changing setenv should be enough to move the most directories.

Have a look at this (http://karaf.922171.n3.nabble.com/Karaf-installation-to-a-read-only-directory-td4040942.html) thread, it should contain all the information you need to know.

**Comment by maggu2810** [comment]
I do not use the instance concept at the moment, but we should also consider to not break it.
Perhaps it could be usefull for demonstrations.
https://karaf.apache.org/manual/latest/users-guide/instances.html

**Comment by kaikreuzer** [comment]
> For me I need to know what is the runtime data (e.g. the current directory data for Karaf and userdata for OH2).

It imho should be ${openhab.home}/userdata and combine the content of what OH2 currently puts there with what Karaf puts in data. So no need to change anything in Karaf on what is inside this folder, it should just only use the same folder as OH2 does. The idea of OH2-userdata and Karaf-data is exactly the same: A folder for all data that is created during runtime.

> I do not use the instance concept at the moment, but we should also consider to not break it.

Agreed. But probably the best place would be to place them as well into userdata. For this it seems we have to wait for the new feature JB mentions in http://karaf.922171.n3.nabble.com/Karaf-installation-to-a-read-only-directory-tp4040942p4040952.html. Until then, I would also be ok to keep it in ${openhab.home}/instances.

**Comment by maggu2810** [comment]
Created a separate issue to track further improvements.

**Comment by maggu2810** [comment]
FYI: I am testing ATM a approach to use pom dependency only for the target platform used by the Eclipse IDE. This is not related to this PR, just for your information.

**Comment by maggu2810** [comment]
@kaikreuzer Are you waiting for me?

**Comment by kaikreuzer** [comment]
I was actually considering to do #379 before adding the branch to the official repo. I think it shoudn't be much effort and is for me a pre-requisite before we ask anybody to test this distribution. I just didn't yet find the time to implement it.

**Comment by maggu2810** [comment]
Ok, did not know that. I thought the blocker has been resolved and the remaining stuff will be done later in separate PRs.

**Comment by kaikreuzer** [comment]
Sorry for not having been clear. Yes, the blocker is resolved, so everything is fine to continue (and to be confident that we are on the right track).
If you prefer, I can move the branch already now, but as I said I wouldn't want to involve anybody in testing before we have #379 in place as well.

**Comment by maggu2810** [comment]
As long as it is a separate branch, we must merge every change of the master branch to that branch manually. So, the move is not really necessary as long as merging is not to time consuming.
If #379 is solved, do we really need still a separate branch for testing?
Just want to know at which time do we know "it is ready to merge in master"?

**Comment by kaikreuzer** [comment]
> As long as it is a separate branch, we must merge every change of the master branch to that branch manually. So, the move is not really necessary as long as merging is not to time consuming.

This will still be the same if we maintain the branch in the main repo. It will only end once it all is merged into the master branch.

> Just want to know at which time do we know "it is ready to merge in master"?

I have entered all that I think is necessary to do before we can proclaim it as the new official distro as issues marked with "karaf": https://github.com/openhab/openhab2/issues?q=is%3Aopen+is%3Aissue+label%3Akaraf

**Comment by kaikreuzer** [comment]
Do they make sense to you, @maggu2810?
I would volunteer for #385 and #386. Is #379 something that you could do?

**Comment by maggu2810** [comment]
> This will still be the same if we maintain the branch in the main repo. It will only end once it all is merged into the master branch.

I have to improve my English skills. This was exact the same I wanted to state.

**Comment by maggu2810** [comment]
> Is #379 something that you could do?

Yepp

**Comment by kaikreuzer** [comment]
Thanks :-)

**Comment by maggu2810** [comment]
Could you add the karaf tag to that PR?

**Comment by maggu2810** [comment]
> If you prefer, I can move the branch already now

Yes, please take that branch, so all changes could be pulled upstream.

**Comment by kaikreuzer** [comment]
I have created https://github.com/maggu2810/openhab2/pull/2 - once this is merged, you can squash your commits of this branch and I will then move it over to the main repo.

**Comment by maggu2810** [comment]
If I squash my branch after merging your maggu2810#2, the author of your PR (bundle) is lost. Isn't it?

**Comment by kaikreuzer** [comment]
You can add an "Also-By" footer to the commit (see https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#The_Commit_Record)

**Comment by maggu2810** [comment]
Done

**Comment by kaikreuzer** [comment]
Thanks - I have created a branch in the official repo now: https://github.com/openhab/openhab2/tree/karaf
So we an continue with PRs on this one.

**Comment by maggu2810** [comment]
Fine!

**Pull request closed without merging**
