### PR TITLE
CalDAV is reported to be OH2-compatible

### PR DESCRIPTION
**Pull request by hakan42**
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>

### CODE REVIEW

**Comment by hakan42** [comment]
Reported by @querdenker2k on original OH1 PR: https://github.com/openhab/openhab/pull/3468#issuecomment-160727115

**Comment by hakan42** [comment]
This is the correct PR with only one commit (and only the intended changes) in it.

**Comment by hakan42** [comment]
Config files amended to remove the prefix and commits squashed into one.

**Comment by kaikreuzer** [comment]
cool, thanks!

**Comment by kaikreuzer** [comment]
@hakan42 This PR made the build fail with 
```
Could not find artifact org.openhab.binding:org.openhab.binding.caldab-command:jar:1.8.0-SNAPSHOT
```
see https://openhab.ci.cloudbees.com/job/openHAB2/430/console.

Could you please have a look?

**Comment by hakan42** [comment]
Oops, typo in artifact name, it should be "caldav-command" and not "caldab-command". I will prepare a fix PR.

**Comment by hakan42** [comment]
Fresh PR #509 created.

**Pull request merged**
