### PR TITLE
initial contribution of MaryTTS bundle

### PR DESCRIPTION
**Pull request by peuter**
Signed-off-by: Tobias Bräutigam <tbraeutigam@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hi Tobias,

Bundles in the namespace org.eclipse.smarthome must be contributed to https://github.com/eclipse/smarthome. But in this case, this will not be successful, as MaryTTS is under LGPL, which is not an accepted license for Eclipse projects.
Anyhow, in Eclipse SmartHome I would like to work on the TTS interfaces and make it more flexible (e.g. to also be able to do a TTS to a Sonos speaker, etc.). Hence for "identical" bundles from openHAB 1, I suggest to make the openHAB 1 version working through the compatibility layer - this will also avoid having to maintain identical code at different places.

**Comment by peuter** [comment]
Ok, but how do I cover the problem that the namespace of the TTSService has changed. Does the combalility layer has to be augmented in order to map org.openhab.io.multimedia.tts to org.smarthome.io.multimedia.tts? And how can I do this?

**Comment by kaikreuzer** [comment]
Yes, the namespace mapping is one of the major features of the compat layer, see https://github.com/openhab/openhab2/tree/master/bundles/core/org.openhab.core.compat1x.
The tts interfaces are indeed not yet part of the compat layer, so this still needs to be implemented.

**Comment by peuter** [comment]
Yes, but how do I do that. Just adding a org.openhab.io.multimedia.tts.TTSService interface to the compability layer does not work, because Audio.getTTSSerrvice is looking for org.eclipse.smarthome.io.multimedia.tts.TTSService. I could change that, but I guess the "smarthome-TTS-Services" won´t work anymore, right? How do I get both TTSServices working?

**Comment by kaikreuzer** [comment]
See e.g. how it is done for Actions: https://github.com/openhab/openhab2/blob/master/bundles/core/org.openhab.core.compat1x/OSGI-INF/actionservicefactory.xml

**Comment by peuter** [comment]
Ok thank, that helps a lot. One question left: How do I read the value of the "os" property of the TTS-Bundle. I have to add this property when registering the service in the ServiceFactory:
```
Dictionary<String, Object> props = new Hashtable<String, Object>();
props.put("os", "any");
ServiceRegistration<org.eclipse.smarthome.io.multimedia.tts.TTSService> serviceReg = context.registerService(org.eclipse.smarthome.io.multimedia.tts.TTSService.class, service, props);
```

**Comment by peuter** [comment]
You can find my current suboptimal solution for reading the property from the correct bundle in my new pull request
https://github.com/openhab/openhab2/pull/166
So any hints how to do it the right way are welcome.

**Pull request closed without merging**
