### PR TITLE
Astro: Documentation added

### PR DESCRIPTION
**Pull request by gerrieg**
Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks a lot! Before I merge: Do you have the rights of this picture, so that it is ok to contribute it?

**Comment by gerrieg** [comment]
I found the picture with google image search. It is from this website: http://www.docter-germany.de/de/anwendungsgebiete/kat/pac/single/cat/astronomie.html

There is no copyright in the metadata of the picture:
```
Gerhard@MacBookPro:~/Downloads: exiftool -a astro.jpg 
ExifTool Version Number         : 9.90
File Name                       : astro.jpg
Directory                       : .
File Size                       : 60 kB
File Modification Date/Time     : 2015:05:22 18:01:46+02:00
File Access Date/Time           : 2015:05:22 18:03:01+02:00
File Inode Change Date/Time     : 2015:05:22 18:01:46+02:00
File Permissions                : rw-r--r--
File Type                       : JPEG
MIME Type                       : image/jpeg
JFIF Version                    : 1.02
Resolution Unit                 : None
X Resolution                    : 100
Y Resolution                    : 100
Quality                         : 80%
DCT Encode Version              : 100
APP14 Flags 0                   : [14], Encoded with Blend=1 downsampling
APP14 Flags 1                   : (none)
Color Transform                 : YCbCr
Image Width                     : 448
Image Height                    : 240
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)
Image Size                      : 448x240
Megapixels                      : 0.108
```

**Comment by kaikreuzer** [comment]
I don't think that the exif data is of any legal importance. If it was taken from "some" website, by default you do not own any rights on the picture...

**Comment by kaikreuzer** [comment]
Please squash the commits as the picture ends up in the repo history anyway!

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
