### PR TITLE
Change karaf.base to match karaf.home

### PR DESCRIPTION
**Pull request by dvanherbergen**
When karaf.base contains the instance data and should not be included in the userdata folder. When ./start.sh clean is used, the userdata folder is deleted by karaf. If karaf.base is pointing to userdata, karaf no longer starts due to the missing directory.
This also sorts out the path problems in #495.

Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
IIRC
* openhab.runtime could be read only during runtime
* openhab.userdata is the directory that is writable at runtime

**Comment by maggu2810** [comment]
Shouldn't we use e.g.
```text
+export KARAF_BASE="${OPENHAB_USERDATA}/karaf"
```

**Comment by maggu2810** [comment]
I didn't get the point. Does openHAB 2 need an existing userdata directory? So we have to prevent the deletion of this one and just delete the content.
A clean should clean all (IMHO) userdata -- all that is written at runtime and that does not need to be existing on the first start.
So ${OPENHAB_USERDATA}/karaf is wrong as the whole userdata content should be removed. Not Karaf only, also the other one (bindings could write to that dir etc.)

**Comment by dvanherbergen** [comment]
Karaf needs an existing KARAF_BASE directory in order to start.
When you start karaf with the clean option, it will delete KARAF_DATA. If KARAF_BASE is nested in KARAF_DATA, that will cause a startup issue.
As far as I understood, KARAF_BASE is used for a an instance and KARAF_HOME is shared between multiple instances. If you have only a single instance, using KARAF_BASE = KARAF_HOME is OK.

**Comment by maggu2810** [comment]
Will have to check later why it has been done as it is.
Could you check #379, too?

**Comment by dvanherbergen** [comment]
Mmm. Not quite clear what the goal was. Anyway, I think there are only 3 options, that will work:
The first one is to use KARAF_BASE=KARAF_HOME. This will mean that there is some karaf instance related information is written to the ${openhab.home}/runtime/karaf during runtime.
The second option would be to nest KARAF_DATA inside KARAF_BASE, e.g. KARAF_BASE = ${openhab.userdata}/karaf   KARAF_DATA = ${openhab.userdata}/karaf/data.
The third one would be to put the KARAF_BASE next to KARAF_DATA .e.g KARAF_BASE = ${openhab.userdata}/karaf-base   KARAF_DATA = ${openhab.userdata}/karaf-data

**Comment by maggu2810** [comment]
> * The first one is to use KARAF_BASE=KARAF_HOME. This will mean that there is some karaf instance related information is written to the ${openhab.home}/runtime/karaf during runtime.

runtime could be read only.

> * The second option would be to nest KARAF_DATA inside KARAF_BASE, e.g. KARAF_BASE = ${openhab.userdata}/karaf   KARAF_DATA = ${openhab.userdata}/karaf/data.

Then we have change the clean option or handle it in setenv ourself (too).
Because the other stuff is not removed.
OR we but our runtime data also under ${karaf.data}, but IIRC that is something Kai does not want, because he want to stay at this layout (userdata in userdata directory and not some below).

> * The third one would be to put the KARAF_BASE next to KARAF_DATA .e.g KARAF_BASE = ${openhab.userdata}/karaf-base   KARAF_DATA = ${openhab.userdata}/karaf-data

The forth option would be to change the karaf clean option.
Instead of doing a <code>rm -Rf "$KARAF_DATA"</code> it seems better to remove the content of the directory only.
It is common, that a directory that could be written to is writable for everyone, but could not be deleted by a non-root user.
Perhaps we should create a JIRA and fix that upstream.

**Comment by dvanherbergen** [comment]
> Perhaps we should create a JIRA and fix that upstream.

OK, so I'll cancel the PR for now.

**Comment by dvanherbergen** [comment]
> Karaf needs an existing KARAF_BASE directory in order to start.
When you start karaf with the clean option, it will delete KARAF_DATA. If KARAF_BASE is nested in KARAF_DATA, that will cause a startup issue.

This [issue] (https://issues.apache.org/jira/browse/KARAF-4241) has been reported to get this resolved.

**Comment by maggu2810** [comment]
Hi @dvanherbergen 

> This issue has been reported to get this resolved.

Could this http://karaf.922171.n3.nabble.com/karaf-4-0-4-clean-not-working-td4044848.html be associated with your changes?

**Comment by dvanherbergen** [comment]
Probably, although I don't immediately see what is wrong in https://github.com/dvanherbergen/karaf/commit/c6beae07723f00bc2fb00bf149d0a14a03a1caf6

**Pull request closed without merging**
