### PR TITLE
initial version of my.openHAB bundle for openHAB 2

### PR DESCRIPTION
**Pull request by kaikreuzer**
This bundle has the following changes over the 1.x version:
- Upgraded to Jetty 9 HTTP Client library
- Independent from 1.x compatibility layer
- Independent from UI bundles
- Automatically uses the local port that is configured in start scripts (no need to configure it separately anymore)
- myopenhab.persist is optional. If not present, state changes of all items will be propagated to my.openHAB. This can be deactivated through by a configuration setting "myopenhab:mode=persistence".

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by hakan42** [comment]
Does this PR work with the current OH2 (as of 10.08.2015)? I built the jar, put it to addons, created a myopenhab.cfg in services and myopenhab.persist in persistence, but the PersistenceManager does not seem to recognize that there is something to be started (only shows "Initializing" for my other persistence services):

grep myopenhab openhab.log:
```
2015-08-10 17:36:22 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'myopenhab.cfg'
2015-08-10 17:53:57 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'myopenhab.cfg'
2015-08-10 17:54:49 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:86   ] - Loading model 'myopenhab.persist'
2015-08-10 17:57:15 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'myopenhab.cfg'
2015-08-10 17:58:06 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:86   ] - Loading model 'myopenhab.persist'
2015-08-10 18:09:49 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'myopenhab.cfg'
2015-08-10 18:10:48 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl:86   ] - Loading model 'myopenhab.persist'

```

snipplet from persistence.log
```
2015-08-10 17:56:59 [DEBUG] [m.p.r.i.PersistenceRuntimeActivator:23   ] - Registered 'persistence' configuration parser
2015-08-10 17:57:59 [DEBUG] [e.s.m.p.internal.PersistenceManager:141  ] - Initializing jpa persistence service.
2015-08-10 17:57:59 [DEBUG] [e.s.m.p.internal.PersistenceManager:141  ] - Initializing rrd4j persistence service.
2015-08-10 17:57:59 [DEBUG] [e.s.m.p.internal.PersistenceManager:141  ] - Initializing logging persistence service.
2015-08-10 17:58:01 [DEBUG] [e.s.m.p.internal.PersistenceManager:141  ] - Initializing mysql persistence service.
2015-08-10 17:58:06 [DEBUG] [e.s.m.p.internal.PersistenceManager:436  ] - Scheduled strategy mysql.everyMinute with cron expression 0 * * * * ?
```

**Comment by kaikreuzer** [comment]
Will have to check. In general, it is supposed to work, yes!
Note that you do not even need a myopenhab.persist file - if you remove it it will simply persist all your items.

**Comment by kaikreuzer** [comment]
@hakan42 I just updated this PR, please have a try if the PersistenceManager now correctly initializes my.openHAB!

**Comment by hakan42** [comment]
I rebuilt the jar from the current PR and installed it into a OH2 installation based on Jenkins build number 304 (the one with the integrated id service). Also, I removed my myopenhab.persist file to see what happens.

Unfortunately, I still cannot see the "activated" debug output from the MyOpenhabService, and also, not the expected "Initializing" debug line from the PersistenceManager. I will investigate further.

**Comment by hakan42** [comment]
Addendum: re-enabling the myopenhab.persist file did not change anything, still no visible activation.

**Comment by kaikreuzer** [comment]
> installed it into a OH2 installation based on Jenkins build number 304

You will need to also build the runtime from the branch, since there were some changes as well. I tried the output from a local Maven build and get:
```
2015-08-13 09:04:29 [DEBUG] [o.e.s.m.p.i.PersistenceManager:141  ] - Initializing myopenhab persistence service.
```
It all seems to work nicely.

**Comment by hakan42** [comment]
O.k., I rebuilt everything from this branch and installed it. Initializing and communicating with the MyOpenhab server works like a charm :smile: 

So, looking forward to see this merged into the main branch :smiling_imp:

**Pull request merged**
