### PR TITLE
add auto-configuring possibility for new cometvisu universal client

### PR DESCRIPTION
**Pull request by peuter**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Isn't the CORS part duplicating https://github.com/eclipse/smarthome/pull/466, i.e. the general mechanism to allow CORS on openHAB 2?

**Comment by peuter** [comment]
You're right is wasn't aware that CORS is already build in. I removed the CORS filter from my branch.

**Comment by kaikreuzer** [comment]
Thanks, could you please squash your commits?

**Comment by peuter** [comment]
Sorry I have no idea how i can get rid off the last merge commit in this PR. Git is refusing to squash this merge. Any Idea, what I can do?

**Comment by kaikreuzer** [comment]
Create a new branch, cherry pick the commit you want, delete the old branch, rename the new branch to have the name of the old one and force push :-)

**Comment by maggu2810** [comment]
If you want to do a rebase + squash, you could (IMHO) also use a branch
with regular merges (from upstream) and using a soft reset + new commit.

2015-11-29 11:48 GMT+01:00 Kai Kreuzer <notifications@github.com>:

**Comment by peuter** [comment]
OK thanks for the hints: new PR #502

**Pull request closed without merging**
