### PR TITLE
MQTT plugin ported from OH1

### PR DESCRIPTION
**Pull request by WetwareLabs**
This add-on implements nearly all functionality of the MQTT plugin found in OH1.

For discussion on the MQTT plugin, please see [the thread here][1]. I didn't get any feedback on the matter there and nobody else seems to be working with this so I decided to port this myself, along with few ideas mentioned there. 

As this is the initiial pull request, I don't really expect this to be accepted in its current form, so this is more like a request for feedback. Especially the documentation needs to be updated, but I can work on that later after I get some comments on the general design.

[1]: https://www.eclipse.org/forums/index.php/t/942318/

Main highlights:
- As opposed to MQTT topics configured as Items (like in OH1), topics are now defined as Things and broker connection is realized as a Bridge (via io.transport.mqtt service).
Example:

```
 Bridge mqtt:bridge:mosquitto [ url="tcp://192.168.1.80:1883", clientId="openhab" ] 
	{
	topic MySensor1_temp [ topicId="/home/sensors/mysensor1/temperature", 	type="state", direction="in" ]
	topic MySensor1_hum  [ topicId="/home/sensors/mysensor1/humidity", 		type="state", direction="in" ]
	topic MySensor1_status [ topicId="/home/sensors/mysensor1/status", 		type="state", direction="in" ]
	topic MyDevice2_switch [ topicId="/home/devices/mydevice2/switch", 		type="command", direction="out" ]
	topic MyDevice3_switch [ topicId="/home/devices/mydevice3/switch", 		type="command", direction="out", transform="MAP(es.map)"]
	topic Openhab_temp 	   [ topicId="/home/openhab/example/temperature", 	type="state", direction="out" ]
	}
```
- Each Item type (String, Integer, Dimmer etc) can be linked to its specific channel of MQTT topic.
Example:
``` 
Number Example_Humidity_FF_MQTT 	"Sensor Humidity [%.1f %%]"					(FF_MQTT)	{ channel="mqtt:topic:mosquitto:MySensor1_hum:number" }
String Example_Status_FF_MQTT 		"Sensor Status [%s]"					(FF_MQTT)	{ channel="mqtt:topic:mosquitto:MySensor1_status:string" }
```

- All topic handlers can receive and send all types (String, Integer, Dimmer) of states and commands, and when a MQTT message is received,  then an effort will be made to cast the payload into all possible Item types. However message will be propagated to only those channels that are active (Item is linked).

- Also EventBus binding and message payload transformation works.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hi Marcus,

Great work, thanks for working on porting the MQTT binding!

> I didn't get any feedback on the matter there

You didn't really give people much time to respond, considering that it is holiday season :-)
I'll try to work through your posts in the cause of this week and provide some feedback. Nonetheless, I think @maggu2810's feedback would be worthwhile as well as he worked with MQTT a lot already.

Just a very first question: Why did you create this PR at openHAB2 and not directly at Eclipse SmartHome? As I think that the MQTT binding is quite a core feature that many people are interested in (especially in the Eclipse IoT community) and there is definitely no issue regarding licenses etc., I would very much suggest to close this PR and rather continue the discussion at Eclipse SmartHome and come up with a PR there. Would that be ok for you?

**Comment by WetwareLabs** [comment]
Hi Kai,

thanks for the comments! Yes, I was quite anxious to get to straight to prototyping, so I started after a bit of waiting, then got into a flow and it turned out that porting wasn't that hard after all, so I ended up finishing most of the stuff in one evening. 

Anyway, I hope most of this code can be re-used in case some changes in the design is needed. I'd be happy to receive feedback from @maggu2810 - it seems he did some porting work for MQTT too, but because of licensing reasons his code won't be published?

As for closing this PR, I have no problems with moving this plugin into SmartHome domain. I just originally thought that the more low-level io.transport-stuff is SmartHome's business and OH takes care of the higher level bindings, but my understanding of the distinction between OH and Smarthome is quite limited at the best :)

Should I re-factor the binding to use SmartHome namespace and then create a new PR, or should we continue discussion there at the previously linked forum thread?

**Comment by kaikreuzer** [comment]
> Should I re-factor the binding to use SmartHome namespace and then create a new PR there, or should we first continue discussion there at the previously linked forum thread?

I think you can start doing the namespace refactoring and we can then also move the discussion from the forum to the code level on the PR. Thanks!

**Comment by ThomDietrich** [comment]
@WetwareLabs @kaikreuzer I am not able to find any other issue or PR for this 2.0 MQTT binding. Could you enlighten me what happened?

**Pull request closed without merging**
