### PR TITLE
Fixed encoding problem for room and device names

### PR DESCRIPTION
**Pull request by habnefrage**
Fix for https://github.com/openhab/openhab2/issues/191

### CODE REVIEW

**Comment by marcelrv** [comment]
@habefrage Cool, thanks for this contribution.
 looks good. Maybe we can extend also one of the  test scripts with this

**Comment by marcelrv** [comment]
@kaikreuzer 
In OH1 we get messages like: 
> openhab » openhab #2805 SUCCESS
> This pull request looks good

For OH2 this is not visible. Is there a specific reason for it?

for this contribution LGTM.

**Comment by kaikreuzer** [comment]
Thanks!

> For OH2 this is not visible. Is there a specific reason for it?

I did not yet configure BuildHive on openHAB 2. @teichsta did this on openHAB 1, I actually do not exactly know, what there is to do and didn't yet spend the time to look into it.

**Comment by kaikreuzer** [comment]
@habnefrage: Before I can merge, you would have to sign your commit/PR, see https://github.com/openhab/openhab2/blob/master/CONTRIBUTING.md#sign-your-work. Thanks!

**Comment by teichsta** [comment]
> I did not yet configure BuildHive on openHAB 2

for the record: BH should now be activated for the openHAB2 Repo as well

**Comment by kaikreuzer** [comment]
Cool, thanks!

**Comment by kaikreuzer** [comment]
@habnefrage The squashing was not fully successful - there are still 2 commits where the first one is unsigned and the second one only contains the sign-off as a message. If you want to try to get it straight, please do so. If you fear that you rather mess things up, then I am also fine with merging it as is.

**Comment by kaikreuzer** [comment]
This looks better, thanks!

**Pull request merged**
